### ISSUE TITLE
React integration?

### ISSUE THREAD

**Issue by promentol** [mean-expert-official/fireloop.io#1]
I was reading this new post
https://github.com/mean-expert-official/loopback-sdk-builder/wiki/8.-(NEW)-FireLoop-API#how-to-create-data

Will there be integration with React? React ecosystem have React-Native, and FireLoop can be really useful for native apps built by React-Native

**Comment by jonathan-casarrubias** [comment]
Hello @promentol thanks for reaching out.

Hey so, in the long term I expect to integrate with different frameworks, once everything is stable in Angular 2 and I create the actual framework, not just the modules as stated in the documentation.

Anyway, once everything is working in Angular 2, I think It will be much easier to port to other frameworks like react.

Also, I'm always leading to where people requests, in other words... Ask your react friends in communities to back this feature request for React and I may release earlier to the open source market.

Cheers
Jon

**Comment by jonathan-casarrubias** [comment]
Now that the FireLoop CLI and the Angular 2 integration is getting mature I'm starting to consider in creating a JavaScript SDK that can be used in other frameworks.

So I have added the enhancement label. 21 days to start considering was not so long. :)

**Comment by kamilml** [comment]
PLEASE REACT!!

this framework looks great :D

do you think this is a good idea use this in production for a bet site? (i want to use this to render my views of game lobbys in real time)

PD. great job mate =)
PD2. i want to use react
PD3. who is working in spanish translation of http://docs.fireloop.io ?

**Comment by beeman** [comment]
@kamilml we would love to address this once the next big release is out (so after 2.2)

Do you by change have a good example of how to neatly integrate an API in a complex React application?

**Comment by osamasaeed** [comment]
I am facing many trouble in integrating Fireloop with Nativescript.
Is there any documentation or example of native app with fireloop ?

**Comment by Hadh** [comment]
Hey, any updates on the matter of integrating React to Fireloop?

**Comment by jonathan-casarrubias** [comment]
Hi @Hadh thanks for reaching out.

Hey so, the only integration we already have is through REST Services, the SDK already creates services to communicate from REACT to LoopBack and backward.

Unfortunately, there is no FireLoop implementation for React and to this point, I don't think it will ever be.

After several inconveniences with LoopBack, I have decided to leave it and therefore FireLoop as well in favor of building a new project from scratch with almost zero dependencies.

I can not provide many details now, but the new project won't build on top of LoopBack and the client SDK will be compatible with any JavaScript framework, therefore you would be able to use it in React, Angular, Vue, Stencil, Native JS, etc.

I apologize with anyone who started a project in FireLoop and I hope that if you were inspired or attracted by the spirit of the project, the new project will contain that same spirit as well, but without dragging those heavy stones behind my project.

https://github.com/mean-expert-official/fireloop.io/issues/137

Cheers
Jon
