### ISSUE TITLE
Fireloop CLI Stops at Project Name Question

### ISSUE THREAD

**Issue by dmastag** [mean-expert-official/fireloop.io#101]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [x] @mean-expert/fireloop@1.0.0-beta.2.5

Write other if any:

#### Please add a description for your issue:
When creating a new project I got stuck at the "Your project name" Question. Not being able to press anything.

I just upgraded to node 8.1 and npm 5.0.3,
Could that be the problem?

**Comment by jonathan-casarrubias** [comment]
@dmastag yes updating the node and npm version usually breaks modules..

Try uninstalling and installing again also the fireloop-cli and let me know if that works for you.

**Comment by jonathan-casarrubias** [comment]
@dmastag I was unable to reproduce this, does your problem persist?
