### ISSUE TITLE
How to debug fireloop nodemon in visual studio code?

### ISSUE THREAD

**Issue by ittechsathish** [mean-expert-official/fireloop.io#102]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [* ] Question

#### What version of this module are you using?
- [ *] 2.1.0-beta.n (2.1 Beta n)
- [ ] Other

Write other if any:
I  am using visual studio code for editing, but i don't know how to start debugger, Could you guys please help me. 
#### Please add a description for your issue:

**Comment by jonathan-casarrubias** [comment]
@ittechsathish try the following thread and see if helps https://github.com/mean-expert-official/fireloop.io/issues/67.

**Comment by ittechsathish** [comment]
Thanks it is working fine.

**Comment by jonathan-casarrubias** [comment]
Cool! I'm closing this one now then..

Cheers
Jon
