### ISSUE TITLE
Third party login is not woring

### ISSUE THREAD

**Issue by ittechsathish** [mean-expert-official/fireloop.io#103]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [* ] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [ ] Other

Write other if any:

When the google redirect to the below url, it is showing the error message.
I dont know how to fix this issue.

/auth/google/callback?code=4/kGbz7jugQZ8eWrIe_HDtu1Qn6_tiNREC6M_91EnhPwo: Error: cookieParser("secret") required for signed cookies

Please help me

#### Please add a description for your issue:

**Comment by ittechsathish** [comment]
app.get('cookieSecret') is not giving any value, so i set some string there , now it is working fine.

app.middleware('session:before', cookieParser('mycodeSecret'));

**Comment by jonathan-casarrubias** [comment]
@ittechsathish thanks for reaching out. Also I'm glad you were able to fix the issue, I believe this was introduced by a LoopBack Update needing to pass the cookieParser.

I'll add that as reference in the SDK documentation

Cheers
Jon
