### ISSUE TITLE
Generating Ionic Client with ionic 3.4.0 crashes and reports "The --v1 and --v2 flags have been removed."

### ISSUE THREAD

**Issue by tohagan** [mean-expert-official/fireloop.io#104]
#### What type of issue are you creating?
- [X ] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [X] Other 1.0.0-beta.2.5

Write other if any:

- Ionic v 3.4.0 (latest) installed.

#### Please add a description for your issue:

Generating an Ionic 2 client now crashes with ... 

```
Creating new Ionic 2 Application: wbm
[ERROR] Sorry! The --v1 and --v2 flags have been removed.
        Use the --type option. (ionic start --help)

        For Ionic Angular projects, try ionic start wbm --type=ionic-angular


Application Status Code: 1

events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at child.Base.destinationPath (C:\nvm\v6.9.1\node_modules\@mean-expert\fireloop\node_modules\yeoman-generator\lib\index.js:637:28)
    at child.install (C:\nvm\v6.9.1\node_modules\@mean-expert\fireloop\node_modules\generator-fireloop\generators\ng2ionic\index.js:61:25)
    at Object.<anonymous> (C:\nvm\v6.9.1\node_modules\@mean-expert\fireloop\node_modules\yeoman-generator\lib\index.js:408:23)
    at C:\nvm\v6.9.1\node_modules\@mean-expert\fireloop\node_modules\run-async\index.js:25:25
    at C:\nvm\v6.9.1\node_modules\@mean-expert\fireloop\node_modules\run-async\index.js:24:19
    at C:\nvm\v6.9.1\node_modules\@mean-expert\fireloop\node_modules\yeoman-generator\lib\index.js:409:9
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
```

**Comment by hellraiserii** [comment]
Hi! 
I'm still having this very same problem in the 1.0.0 beta 2.6 version which was supposed to fix it.
I believe it was because @tohagan got rid of the '--v2' flag in .js generated code instead of the .ts code. In the end, the change was never commited to master by @jonathan-casarrubias. Please correct me if I'm wrong, I'm kind of newbie just yet in these matters.

**Comment by jonathan-casarrubias** [comment]
@hellraiserii thanks for reaching out, I will verify but your argument makes sense, so if that is the case I'll try to add that to the TS file, compile it and publish with the patch asap.

cheers
Jon

**Comment by topalavlad** [comment]
Is there any workaround for this? I just started using fireloop and was stopped by this :)
FireLoop Version: 1.0.0-beta.2.6

It seems ok after I replaced the first line with the second one in `/usr/local/lib/node_modules/@mean-expert/fireloop/node_modules/generator-fireloop/generators/ng2ionic/index.js:`
```
this.spawnCommand('ionic', ['start', answers.name, '--v2'], { shell: true })

this.spawnCommand('ionic', ['start', answers.name, '--type=ionic-angular'], { shell: true })
```

**Comment by jonathan-casarrubias** [comment]
Hey guys sorry for the delay, I removed the --v2 flag you should be able to make it work on version 

1.0.0-beta.2.6

Regards

**Comment by tohagan** [comment]
I think we can close this now.
