### ISSUE TITLE
After remote is not working in Mode@l

### ISSUE THREAD

**Issue by ittechsathish** [mean-expert-official/fireloop.io#106]
#### What type of issue are you creating?
- [* ] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

  hooks: {
    beforeSave: { name: 'before save', type: 'operation' },
    afterRemoteCreate: { name: 'create', type: 'afterRemote' }
  },

in the class created a method.

  afterRemoteCreate(context: any, user: any, next: any) {
    console.log('after user create');
  }

**Comment by jonathan-casarrubias** [comment]
Hey @ittechsathish thanks for reaching out, I will verify the issue asap

Cheers
Jon

**Comment by luisomoreau** [comment]
Hello!
Any solution?
I have the same issue
Thanks

**Comment by eduardoarn** [comment]
I have the same problem
Any solution ?

Minho's palatative solution was to use the this definition method:

`afterRemoteSave: {name: 'after save', type: 'operation'},`

but I really need to run the method only on creation and not update

**Comment by jonathan-casarrubias** [comment]
Hi guys

Hey so, I really want to apologize for saying this but I'm stopping the support for FireLoop or any LoopBack module I built.

I'm working on a new project from scratch that of course is not built on top of LoopBack or anything else, this new project will also provide a SDK but now it won't be FrameWork specific, therefore you should be able to use it in Angular 5, React, Vue or even plain JavaScript projects


I apologize if you started a project on FireLoop, here I give a more detailed explanation:
https://github.com/mean-expert-official/fireloop.io/issues/137
