### ISSUE TITLE
Operation hook example for beforeSave  (create, upsert) in typescript?

### ISSUE THREAD

**Issue by neolution** [mean-expert-official/fireloop.io#108]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [x] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [X] Other (loopback 3.x)
Write other if any:

#### Please add a description for your issue:

I didn't find an example how to use the "beforeRemote"-method "create" for an model in fireloop (typescript)?

How to reference to another model inside this function, where I previously set a relation to another model with "hasmany" ?

Any examples are welcome. Thank you!

**Comment by chrno04** [comment]
if you mean the method in the model.ts in loopback ( generate for the fireloop model) for example to use the method beforeSave ( is already generate with fireloop) 

```
beforeSave(ctx: any, next: Function): void {
    //obtain the model data of ctx
     let data = JSON.parse(JSON.stringify(ctx.instance));

   //access another model inside the method
    this.model.app.models.MyModel2.find({ //filter  }, (err: any, response: any) => {
       console.log(response);
       let mymodel = JSON.parse(JSON.stringify(response));
      // your logic
    });
  
    console.log('MyModel: Before Save');
    next();
  }
```
you can use `this.model.app.models` to get access to the models in loopback and querying like in the oficial tutorial of loopback [Querying data](http://loopback.io/doc/en/lb3/Querying-data.html), for access a related model you use the filter 

 `{ include : [ {relation: "RelatedModel" } ] }`

and the access the model of hasmany relation like  mymodel.relatedmodel[ ]

```
 for (let relatedmodeldata of mymodel.relatedmodel) {
            console.log(relatedmodeldata);
      }
```

**Comment by neolution** [comment]
Ok Thank you for your fast response. 

Do you have a solution for my remotemethod "create" also?

Update: I solved it.

@Model({
  hooks: {
    beforeSave: { name: 'before save', type: 'operation' },
    **beforeRemoteCreate: { name: 'create', type: 'beforeRemote' }**
  },

class Booking {
  // LoopBack model instance is injected in constructor
  constructor(public model: any) { }

  // Example Operation Hook
  beforeSave(ctx: any, next: Function): void {
    console.log('Booking: Before Save');
    next();
  }

  **beforeRemoteCreate(ctx: any, booking: any, next: Function) {
    console.log('beforeCreate');
...
}**
