### ISSUE TITLE
Documentation page shows TIMED OUT

### ISSUE THREAD

**Issue by appunnicer13** [mean-expert-official/fireloop.io#112]
#### What type of issue are you creating?
- [*] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [*] 2.1.0-beta.n (2.1 Beta n)
- [ ] Other

Write other if any: Documentation timed Out

#### Please add a description for your issue: Seems like http://docs.fireloop.io/en/api/ is  not working anymore.

**Comment by jonathan-casarrubias** [comment]
@appunnicer13 I had a CC expiration issue, but I have just fixed that and now all the sites are up and running again...

Thanks for reporting

cheers
Jon
