### ISSUE TITLE
How do I implement resetPassword with FireLoop using the default user-model?

### ISSUE THREAD

**Issue by NicolasDurant** [mean-expert-official/fireloop.io#113]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [x] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [x] Other

Write other if any:
2.1.0
#### Please add a description for your issue:

So in my /xyz.component.ts, I'm calling the resetPassword method from /user.ts. In the LoopBack documentation it says:

> Calling User.resetPassword ultimately emits a resetPasswordRequest event and creates a temporary access token.

But how do I catch the event? If I try to apply .on('resetPasswordRequest', ()=>{....}) it tells me there is no 'on' for the UserApi.

**/xyz.component.ts**
` private resetPassword(){
    this.userApi.resetPassword({email: this.userName}).subscribe((data : any)=>{
        console.log(data);
    },(error : any) => {
        this.error = error;
      }
    );
    console.log("error: " , this.error);
  }`

**/user.ts**
`  public resetPassword(options: any, customHeaders?: Function): Observable<any> {
    let _method: string = "POST";
    let _url: string = LoopBackConfig.getPath() + "/" + LoopBackConfig.getApiVersion() +
    "/Users/reset";
    let _routeParams: any = {};
    let _postBody: any = {
      options: options
    };
    let _urlParams: any = {};
    let result = this.request(_method, _url, _routeParams, _urlParams, _postBody, null, customHeaders);
    return result;
  }`

**Comment by MROALI** [comment]
I have the same question as above... 
how to intercept the reset password request. i added the function on the common\account.ts but it's not intercepted
class Account {
  // LoopBack model instance is injected in constructor
  constructor(public model: any) {

  }
  
  public resetPasswordRequest(info:any) {
    console.log("sent new password by mail");
  }
}

**Comment by MROALI** [comment]
I found the solution for my account model which extend the user model : 

In fact you must to implement a remote method in the model.ts file for example :
1- add a new remote method to the model.ts
   **remotes: {
        resetPasswordRequest: {
      returns : { arg: 'result', type: 'array' },
      http    : { path: '/reset', verb: 'post' }
    }
}**

2- then add the method : 
  **public resetPasswordRequest(info:any) {
    let result:Array<string>;
    console.log("sent new password by mail");
    return result;
  }**

2- add an acl to authorize the call of the new function by everyone : in the model.json
**"acls": [
    {
      "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW",
      "property": "resetPasswordRequest"
    }
]**

tell if it works in your case.

**Comment by NicolasDurant** [comment]
Hey Mroali,

that already helped me alot. May I ask how you execute the
resetPassword()-method from your account model?
I seem to be doing it wrong, because when I execute the resetPassword() on
my Customer Api (same as your account, extended model from the default user
model), it still does not trigger the method resetPasswordRequest()
implemented in the customer.ts file.

Thanks for any help!

2017-08-17 16:56 GMT+02:00 MROALI <notifications@github.com>:

**Comment by MROALI** [comment]
Bonjour Nicolas, 
I removed my old comment because it is not the good way to do it. 
In fact the solution is too easy : it consist of adding the following in the constructor of the customer model :  

constructor(public model: any) {
       **model.on('resetPasswordRequest', function(info:any) {
          console.log("test");  
  });**

**Comment by NicolasDurant** [comment]
Wow! That's amazing and depressing at the same time.
Thank you so much for your quick responses!
Solved my problem, have a great day :)
