### ISSUE TITLE
Validation model data

### ISSUE THREAD

**Issue by MROALI** [mean-expert-official/fireloop.io#115]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [x ] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [ x] Other

Write other if any:
Release 1.0.0-beta.2.6
#### Please add a description for your issue:

how can i add model data validation as mentionned in https://loopback.io/doc/en/lb3/Validating-model-data.html
i tried to add this line in the constructor of my Account.ts  and nothing happened: 
model.validatesLengthOf('password', {min: 7});  //but not working

Please tell me how to do in the right way.

**Comment by jonathan-casarrubias** [comment]
Hi @MROALI thanks for reaching out,

Hey so... That actually should work, the FireLoop model constructor represents the function you usually see in a LoopBack model

````js
module.exports = function(Model) {
    Model.validatesLengthOf('password', {min: 7});
}
````

equals

````js
constructor(model: any) {
    model.validatesLengthOf('password', {min: 7});
}
````

So technically that should work, I'll try to verify if I can replicate the issue and fix it if necessary but at first sight I'm out of ideas it should just work lol, lets see.

Cheers
Jon

**Comment by MROALI** [comment]
Hello @jonathan-casarrubias ,
It seems that it is not working. 
1- I added model.validatesLengthOf('password', {min: 7}); in my class constructor
2- I tried to create an account with 3 characters password length
3- No error returned by the api.
Normally it must return the default message error : 
min: too short

Do you any idea. 
My model name is account and it's extending the user default model, i don't know if it's related or not.

thank you in advance

MROALI

**Comment by jonathan-casarrubias** [comment]
well that is really strange, I'll try to verify as soon as I can.. not sure being a user based model would affect, it is just odd because the model parameter was never mutated so it is what loopback is sending as model, therefore the validatesLengthOf should work, not sure if we are not seeing something obvious here

**Comment by MROALI** [comment]
Hello @jonathan-casarrubias, 

I think i have an idea about the problem. It's not related to fireloop. 
It's related to loopback, the problem is that loopback is validating the length of the password hash, and not the password by it self. 

So if i use for example model.validatesLengthOf('password', {min: **100**});  ==> the validation works.
but for model.validatesLengthOf('password', {min: **7**}); ==> validation is not working because the length of the hash is always more than 7.

https://github.com/strongloop/loopback/issues/251

If you have any  hack for doint the job i'll be thankfull .

Best regards
MROALI

**Comment by jonathan-casarrubias** [comment]
Hi @MROALI  thanks for reaching out.

Hey so, I really want to apologize for saying this but I'm stopping the support for FireLoop or any LoopBack module I built.

I'm working on a new project from scratch that of course is not built on top of LoopBack or anything else, this new project will also provide a SDK but now it won't be FrameWork specific, therefore you should be able to use it in Angular 5, React, Vue or even plain JavaScript projects


I apologize if you started a project on FireLoop, here I give a more detailed explanation:
https://github.com/mean-expert-official/fireloop.io/issues/137
