### ISSUE TITLE
How can I call a remot method?

### ISSUE THREAD

**Issue by pmc-sstaehle** [mean-expert-official/fireloop.io#116]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [X] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [ X] Other ==> 1.0.0-beta.2.6

Write other if any:

Hi there, first of all I wanted to thank you for this nice framework. But when I digging a little bit deeper into the logic I'm standing in front of a strange problem. My steps to reproduce:
1. Create a new (custom) remote method in my loopback class:
`...
testRemote: {
      returns : { arg: 'result', type: 'string' },
      http    : { path: '/testRemote', verb: 'get' }
    }
...
//Test
  testRemote(next: Function): void {
    next('here i am');
  }`
2.  Rebuild the fireloop SDK
3. Wanted to call my new testRemote via:
`this.rt.onReady().subscribe((status: string) => {
        this.absRef = this.rt.FireLoop.ref<Absence>(Absence);
        this.absRef.remote('testRemote').subscribe((res: string) => {
          console.log('Hello: ' + res);
        });
        this.absRef.onRemote('testRemote').subscribe((res: string) => {
          console.log('Hello: ' + res);
        });
      });`

Unfortunaltely this does not work. Can please somebody tell me what's the problem or what I am doing wrong?
Thanks!

**Comment by WhatzzUp** [comment]
Hey @pmc-sstaehle,

first of all i guess you created sth like this:

```javascript
@Model({
  remotes: {
    testRemote: {
      returns: {
        arg: 'result', type: 'string'}, http: {path: '/testRemote', verb: 'get'}
    }
  }
})

class YourClassName {
  testRemote(next: Function): void {
    next('here i am');
  }
}

module.exports = YourClassName;
```

After you rebuild the fireloop SDK, a new custom services has been created at your sdk path:
> path/to/your/sdk/service/custom/YourClassName.ts

The created file is named by your class.

To use your custom remote method, you only need to inject this service inside your class.

```javascript
import {YourClassName} from "path/to/your/sdk/service/custom/YourClassName"

class AnotherClass {
  constructor(public myClass: YourClassName) { //inject your custom service with your testRemote method
    myClass.testRemote().subscribe((result: string) => { //call your testRemote method
      console.log(result)
    })
  }

public anotherMethod() {
  this.rt.onReady().subscribe((status: string) => {
    this.absRef = this.rt.FireLoop.ref<Absence>(Absence);
    
    this.myClass.testRemote().subscribe((result: string) => { //call your testRemote method
      console.log(result)
    });
  })

}
}
```
I hope I could help you,

Cheers

Chris

**Comment by pmc-sstaehle** [comment]
Yes, thats exactly what I wanted to achieve!
Thank you, @WhatzzUp

**Comment by NicolasDurant** [comment]
If Chris answered your question, you might want to close the issue unless there's another question related to it ;) @pmc-sstaehle

**Comment by jonathan-casarrubias** [comment]
@pmc-sstaehle are you good with this issue? are we able to close it?

**Comment by pmc-sstaehle** [comment]
Thank you, it's fine! My problem is solved. And I'm gonna close the issue.
