### ISSUE TITLE
Loopback Model in JS not TypeScript

### ISSUE THREAD

**Issue by plunkettscott** [mean-expert-official/fireloop.io#117]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [x] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [x] Other

Write other if any:
1.0.0-beta.2.7

#### Please add a description for your issue:

The documentation shows that when running `fireloop model MyModel` and completing the prompt, the created model should be in TypeScript, however, it appears that this is not the case. I've ran it a few times now. Tried updating my Fireloop, but still no TypeScript. Is there something I am missing here?

Scott

**Comment by Boromir1994** [comment]
After finishing adding properties on next empty property just press "Enter" and model will be in TypeScript. Above row "Property name:" Loopback make hint for you: "Enter an empty property name when done."

**Comment by jonathan-casarrubias** [comment]
Hey @plunkettscott were you able to generate the model? can I close this issue

**Comment by plunkettscott** [comment]
I can generate the model, however, it is not in TypeScript. The issue wasn't generating it. I was under the impression that models in Loopback were supposed to be in TypeScript? Is that not the case, @jonathan-casarrubias?

**Comment by bitingedgemick** [comment]
@plunkettscott can you show us what is being generated?

**Comment by jonathan-casarrubias** [comment]
Hi guys thanks for reaching out.

Hey so, I really want to apologize for saying this but I'm stopping the support for FireLoop or any LoopBack module I built.

I'm working on a new project from scratch that of course is not built on top of LoopBack or anything else, this new project will also provide a SDK but now it won't be FrameWork specific, therefore you should be able to use it in Angular 5, React, Vue or even plain JavaScript projects


I apologize if you started a project on FireLoop, here I give a more detailed explanation:
https://github.com/mean-expert-official/fireloop.io/issues/137
