### ISSUE TITLE
Authentication to the LB 3.0

### ISSUE THREAD

**Issue by ptesar-xyndata** [mean-expert-official/fireloop.io#118]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [x] 2.1.0-beta.n (2.1 Beta n)
- [ ] Other

Write other if any:

Authentication using loopback-component-realtime is not working correctly.

Even the token is accepted and emited, by debuging of backend I get this errors: 

loopback:security:access-context --Context scopes of undefined()-- +0ms
  loopback:security:access-context   method-level: ["DEFAULT"] +1ms
  loopback:security:access-context ---AccessContext--- +8ms
  loopback:security:access-context principals: [] +0ms
  loopback:security:access-context modelName Customer +0ms
  loopback:security:access-context modelId null +0ms
  loopback:security:access-context property find +0ms
  loopback:security:access-context method find +0ms
  loopback:security:access-context accessType READ +0ms
  loopback:security:access-context --Context scopes of undefined()-- +0ms
  loopback:security:access-context   method-level: ["DEFAULT"] +0ms
  loopback:security:access-context accessScopes ["DEFAULT"] +0ms
  loopback:security:access-context accessToken: +0ms
  loopback:security:access-context   id "$anonymous" +0ms
  loopback:security:access-context   ttl 1209600 +0ms
  loopback:security:access-context   scopes ["DEFAULT"] +1ms
  loopback:security:access-context getUserId() undefined +0ms
  loopback:security:access-context isAuthenticated() false +0ms
  loopback:security:access-context ---AccessContext--- +1ms
  loopback:security:access-context principals: [] +0ms
  loopback:security:access-context modelName Customer +0ms
  loopback:security:access-context modelId null +0ms
  loopback:security:access-context property find +0ms
  loopback:security:access-context method find +0ms
  loopback:security:access-context accessType READ +0ms
  loopback:security:access-context --Context scopes of undefined()-- +0ms
  loopback:security:access-context   method-level: ["DEFAULT"] +1ms
  loopback:security:access-context accessScopes ["DEFAULT"] +0ms
  loopback:security:access-context accessToken: +0ms
  loopback:security:access-context   id "$anonymous" +0ms
  loopback:security:access-context   ttl 1209600 +0ms
  loopback:security:access-context   scopes ["DEFAULT"] +0ms
  loopback:security:access-context getUserId() undefined +0ms
  loopback:security:access-context isAuthenticated() false +0ms
  loopback:security:access-context ---AccessRequest--- +2ms
  loopback:security:access-context  model Customer +0ms
  loopback:security:access-context  property find +0ms
  loopback:security:access-context  accessType READ +0ms
  loopback:security:access-context  permission DENY +0ms
  loopback:security:access-context  isWildcard() false +0ms
  loopback:security:access-context  isAllowed() false +1ms
@mean-expert/loopback-component-realtime: FireLoop server error: "401 Unauthorized Event"

Can someone help?

Thx.

**Comment by ptesar-xyndata** [comment]
I have searched further and the function : 

FireLoop.checkAccess

have ctx.socket.token empty, even when I get : 
@mean-expert/loopback-component-realtime: Internal server client is authenticated
@mean-expert/loopback-component-realtime: Internal client is authenticated

**Comment by jonathan-casarrubias** [comment]
@PatrikTes the internal server and clients are not related to Angular clients, these are for internal mechanisms.

I have just added a documentation for authentication.

https://github.com/mean-expert-official/fireloop.io/wiki/Authentication

Make sure you have the auth enabled and you need to also make sure you create real-time connections after you authenticate and not prior.

Cheers
Jon

**Comment by ptesar-xyndata** [comment]
YES! It WORKS!!!! Thank you Jonathan!
