### ISSUE TITLE
Model class Loopback typings

### ISSUE THREAD

**Issue by Nosfistis** [mean-expert-official/fireloop.io#120]
#### What type of issue are you creating?
- [ ] Bug
- [x] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [x] Other (1.0.0-beta2.7)

#### Please add a description for your issue:
Loopback currently does not ship with typings, however there are typings in the DefinitelyTyped repo. I guess most of these do not work well with Fireloop's structure, but would it be possible to provide some more typings? Having `any` on all native arguments (such as the model in a model class's constructor) is not assisting with Typescript much.

**Comment by jonathan-casarrubias** [comment]
@Miced It is a shame, but the LB4 refactor affected/changed all the plans, actually we were mapping LB typings based on that, but the current plans is to wait for the LB4 developer version to be released, and then we will refactor the SDK Builder and the Real-Time Components on top of that.

By that moment all of our typescript work would be sadly deprecated.

**Comment by Nosfistis** [comment]
@jonathan-casarrubias I understand your point, indeed I browsed the LB4 notes last week and it seems better to wait for the official integration.
