### ISSUE TITLE
Non-public models should generate a TS model

### ISSUE THREAD

**Issue by Nosfistis** [mean-expert-official/fireloop.io#122]
#### What type of issue are you creating?
- [ ] Bug
- [x] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [x] Other

Write other if any: 1.0.0-beta.2.7

#### Please add a description for your issue:
In order to use TS auto-completion in loopback, I am currently using the MyModelInterface files generated in the UI SDK. However, if a model is not public (but in the common folder) it does not generate a TS "interface" file. I think any model in the "common" folder should generate one, since there can be a neat distinguish between non-public ones if they are put in the "server" folder.

**Comment by jonathan-casarrubias** [comment]
@Miced well I think that sounds fair, not exposing API services but the model I think it makes sense.

I think we need to also move this one to the SDK repo
