### ISSUE TITLE
Integrate HttpClient instead of Http

### ISSUE THREAD

**Issue by Nosfistis** [mean-expert-official/fireloop.io#124]
#### What type of issue are you creating?
- [ ] Bug
- [x] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [x] Other

Write other if any: 1.0.0-beta.2.7

#### Please add a description for your issue:
Angular 4.3 added [HttpClient](https://angular.io/guide/http), a replacement for Http which allows for easier and better requests. Are there any plans for the generated services to use it instead of Http? Among other things, it allows easy intercepting of requests.

**Comment by jonathan-casarrubias** [comment]
Please follow this issue https://github.com/mean-expert-official/loopback-sdk-builder/issues/497
