### ISSUE TITLE
Can't catch some events

### ISSUE THREAD

**Issue by alex-w-dev** [mean-expert-official/fireloop.io#127]
#### What type of issue are you creating?
- Bug

#### Please add a description for your issue:
- [ ] I can't catch 'child_changed' event! i think it should works as like as 'child_removed' (child_removed works).
- [ ] Also I catch 'child_added' on all items (old and new), but added just one. I think it works incorrectly ...

please correct me , if i'm not right
#### Used next:
[Listen-‘child_added’-Event](http://docs.fireloop.io/en/api/#Listen-‘child_added’-Event)
[Listen-‘child_changed’-Event](http://docs.fireloop.io/en/api/#Listen-‘child_changed’-Event)

![1](https://user-images.githubusercontent.com/9738033/31344030-e5bfffb2-ad2a-11e7-9be1-dc7ca481a56a.gif)

**Comment by jonathan-casarrubias** [comment]
Hi @alexander-w-dev thanks for reporting, the child_changed is not actually implemented, I'm not sure when we added that into the docs but it should not be there. sorry for that.

About the child_added I just verified and it does have a problem, it is the default limit from the on method. for now you can just work around the issue by passing a filter for that with limit 1.

I'll try to fix these issues asap, I just need to let you know that the project slowed down due the breaking changes on LB4, we will be fully refactoring the project once the developer version of LB4 is ready

**Comment by alex-w-dev** [comment]
@jonathan-casarrubias thank you for feedback !
child_added - OK, i will use filter
child_change - OK too ... i think it can be replaced by "change" with filter
