### ISSUE TITLE
Relation having same name as foreign key results fails Angular build

### ISSUE THREAD

**Issue by Nosfistis** [mean-expert-official/fireloop.io#128]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [x] Other

Write other if any:
1.0.0-beta.2.7

#### Please add a description for your issue:
Having a model with a relation whose name and foreignKey are the same (so that the JSON produced has either number or the object) results in incorrect type in Angular, since it generates duplicate entries.

**Comment by jonathan-casarrubias** [comment]
Hi @Miced  thanks for reaching out.

Hey so, I really want to apologize for saying this but I'm stopping the support for FireLoop or any LoopBack module I built.

I'm working on a new project from scratch that of course is not built on top of LoopBack or anything else, this new project will also provide a SDK but now it won't be FrameWork specific, therefore you should be able to use it in Angular 5, React, Vue or even plain JavaScript projects


I apologize if you started a project on FireLoop, here I give a more detailed explanation:
https://github.com/mean-expert-official/fireloop.io/issues/137
