### ISSUE TITLE
REST API documentation needed on http://docs.fireloop.io/en/api/

### ISSUE THREAD

**Issue by tohagan** [mean-expert-official/fireloop.io#129]
#### What type of issue are you creating?
- [ ] Bug
- [X] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

I can only find documentation for the FireLoop Real-time api but not the REST api that I understand it includes.  Can you please add documentation for the REST api to your wiki or make it more obvious where it resides.  This is a major area of confusion for Fireloop.

Thanks

**Comment by tohagan** [comment]
The only way I know that the REST api existed was via a reply made in the community questions. Apart from that it was unknowable AFAIK.

-   https://github.com/mean-expert-official/fireloop.io/issues/22#issuecomment-289494150

**Comment by Nosfistis** [comment]
As mentioned in the comment, the REST api follows the documentation of Loopback. You can read about it on the [official Loopback docs](http://loopback.io/doc/en/lb3/).

**Comment by jonathan-casarrubias** [comment]
Hi guys

Hey so, I really want to apologize for saying this but I'm stopping the support for FireLoop or any LoopBack module I built.

I'm working on a new project from scratch that of course is not built on top of LoopBack or anything else, this new project will also provide a SDK but now it won't be FrameWork specific, therefore you should be able to use it in Angular 5, React, Vue or even plain JavaScript projects


I apologize if you started a project on FireLoop, here I give a more detailed explanation:
https://github.com/mean-expert-official/fireloop.io/issues/137
