### ISSUE TITLE
How to use typesafe PersistedModel and Validatable on model type

### ISSUE THREAD

**Issue by tohagan** [mean-expert-official/fireloop.io#130]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [X] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

I’ve posted this StackOverflow question and also contacted Raymond Camden in the hope that I can find out how to do typesafe Fireloop on both server and client side. All your examples show `model:any` which kind of defeats the purpose of having Typescript so trying to figure out which type I can import to use both PersistedType methods and Validatable methods. So far my attempts have hit brick walls as I explain below ...

https://stackoverflow.com/questions/47222821/how-to-use-type-check-loopback-fireloop-persistedmodel

**Comment by jonathan-casarrubias** [comment]
@tohagan thanks for reaching out,

Hey so... We were actually working on mapping the good old LoopBack but stopped our work on this version of FireLoop due the LoopBack 4 announcement.

We won't be supporting this version for much longer, we are already working on a compatible version for LB4.

Anyway, for this specific issue we had good progress so, you might be able to import

````js
import { ModelConstructor } from '@fireloop/core'

class MyModel {
  constructor(model: ModelConstructor) {}
}
````

I hope this helps you improve your current experience.

Regards
Jon

**Comment by tohagan** [comment]
Thanks!  Looking forward to LB4 Fireloop.

Would be nice to include `@fireloop/core` in the template used to generate your fireloop app.
I had no idea that this package existed.

**Comment by tohagan** [comment]
I found that `ModelConstructor` validation methods were missing arguments like `{ message: 'my error message' }` and methods like `exists()` returned `Promise<any>` instead of `Promise<boolean>`.  The type definitions in [Loopback 3 Type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/loopback/index.d.ts) were more complete but were unusable unless fixed.

In the end I used ..

```
# Used modified types from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/loopback/index.d.ts
import { Validatable } from '../types/validatable';
import { PersistedModel } from '../types/loopback';     # Fixed static methods and return types.

constructor(public MyModel: Validatable | PersistedModel) {
  let Model = MyModel as Validatable;
  Model.validatesLengthOf('code', { min: 6, max: 80, message: { min: 'too short',  max: 'too long' } });
  Model.validatesFormatOf('email', { with: this.reEmail, message: 'invalid email address', allowNull: false });
  Model.validatesInclusionOf('role', { in: RoleNames, message: 'is not valid' });
}
```

And in later methods ..

```
let Model = this.MyModel as PersistedModel;    
Model.exists(code).then(isFound => { ... });  // knows that isFound is boolean
```
