### ISSUE TITLE
Cannot set id with "idInjection": false and  "id": true

### ISSUE THREAD

**Issue by tohagan** [mean-expert-official/fireloop.io#132]
#### What type of issue are you creating?
- [X] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?

    "@mean-expert/boot-script": "1.0.0",
    "@mean-expert/loopback-component-realtime": "1.0.0-rc.9.3",
    "@mean-expert/loopback-sdk-builder": "2.1.0-rc.12.1",
    "@mean-expert/model": "1.0.9",

Write other if any:

#### Please add a description for your issue:
Attempting to set the id property throws:

     TypeError: Cannot set property id of #<ModelConstructor> which has only a getter 

NOTE: I'm not referencing `ModelConstructor` anywhere in my code so I'm assuming Fireloop has a definition for ModelConstructor that makes id read only which I believe is incorrect .

Example model.
```
{
  "name": "MyThing",
  "plural": "MyThingies",
  "base": "PersistedModel",
  "idInjection": false,
  "options": {
    "validateUpsert": true,
    "postgresql": {
      "schema": "public",
      "table": "thing"
    }
  },
  "properties": {
    "id": {
      "id": true,
      "type": "string",
      "required": true,
      "length": 80,
      "postgresql": {
        "dataType": "varchar"
      }
    },
  ...
}
```

**Comment by tohagan** [comment]
Fixed after I rebuilt the database!

**Comment by jonathan-casarrubias** [comment]
Hi @tohagan thanks for reaching out.

Hey so, I really want to apologize for saying this but I'm stopping the support for FireLoop or any LoopBack module I built.

I'm working on a new project from scratch that of course is not built on top of LoopBack or anything else, this new project will also provide a SDK but now it won't be FrameWork specific, therefore you should be able to use it in Angular 5, React, Vue or even plain JavaScript projects


I apologize if you started a project on FireLoop, here I give a more detailed explanation:
https://github.com/mean-expert-official/fireloop.io/issues/137
