### ISSUE TITLE
FireLoop NEXT (FINAL ANNOUNCEMENT)

### ISSUE THREAD

**Issue by jonathan-casarrubias** [mean-expert-official/fireloop.io#137]
Final Announcement
===================

Hello guys, through this final announcement I want to communicate that I'm definitely stopping the support for the FireLoop project and all of the modules related to LoopBack like the SDK Builder.

I know I just published a couple of months ago that I was working on building FireLoop on top of LoopBack 4 again, but after some time, I found that following that path was a really wrong desition and I decided that I need to move on and completely leave LoopBack behind.

Therefore, since I'm leaving LoopBack as my back-end framework choice I'm leaving everything I built for them as well, hoping that these modules remain helping many of you to build applications while using LoopBack and maybe some of you might continue the work by forking my repos and modules that will be kept alive.

# Ooooook..... so... What is next?
After having an enormous amount of learnings while building all of those modules, even building a platform composed from other frameworks and some core integration modules.

I have decided to start a new project from scratch, following the same FireLoop spirit but without any ties, that will allow me to literally have the entire control and avoid a bunch of unexpected errors due to the huge amount of the dependencies.

# Then why not calling it FireLoop?
Because first of all it won't be built on top of LoopBack, and second because it won't imitate the FireBase API.

The new project is RPC/MicroServices oriented and is built from scratch with almost zero dependencies and with its own `Service Oriented Architecture` implementation providing a `Remote Call Procedure` API for communication between these services.

And for that reason, this new project is unable to be called FireLoop.

# Will my current FireLoop apps work on this new Project?
Unfortunately, it won't work on this new project, nor on LB4. And that is one of the reasons I'm starting this new project because I simply must not delegate the stability of my project to others.

# This project... What is going to have in common with FireLoop?
First is built on TypeScript but now, it will also be compatible with plain JS projects (for those hatin' TS)

Second, it will provide client SDK but this time won't be Angular specific but it will be compatible with any JavaScript front-end framework (React, Angular, Vue, Stencil, etc), even in plain JavaScript projects.

# will it continue using http/rest and socket.io/websocket as transportation?
I'm also leaving socket.io and this new project is being built using the latest technology features like async/await, WebWorkers, EventStreams and HTTP2 using gRPC.

# Is this new project an actual MicroServices platform or just another REST API Services framework
Of course, this is a true SOA project, each app / service runs on separated processes and communication between these services and clients can be done through the provided Remote Procedure Call (RPC) API.

Therefore if any of your apps crash, the rest of the loaded applications will remain up and running, then the server will try to start your crashed app again.

# It sounds like there is already some progress with this.
Yes, that is the reason I'm publishing this final announcement.

# When can we know more details?
FireLoop is done from now and so on, no more details will be communicated on that.

About the new project, we already have a very good progress and we even have a name, but will be posting details about it once we do some branding.

Thanks to all for your support on this project. I don't really want to say that this project is dead.

It is just a re-born as a new project but now with its own personality.

Cheers
Jon

**Comment by jonathan-casarrubias** [comment]
Final Announcement
===================

Hello guys, through this final announcement I want to communicate that I'm definitely stopping the support for FireLoop project and most of the modules related to LoopBack.

I know I just published a couple of months ago that I was working on building FireLoop on top of LoopBack 4 again, but after some time, I found that following that path was a really wrong desition and I just decided that I need to move on and leave LoopBack behind.

Therefore, since I'm leaving LoopBack as my back-end framework choice I'm leaving everything I built for them as well, hoping that these modules remain helping many of you to build applications while using LoopBack and maybe some of you might continue the work by forking my repos and modules that will be kept alive.

# Ooooook..... so... What is next?
After having an enormous amount of learnings while building all of those modules, even building a platform composed from other frameworks and some core integration modules.

I have decided to start a new project from scratch, following the same FireLoop spirit but without any ties, that will allow me to literally have the entire control and avoid a bunch of unexpected errors because of the huge amount of the dependencies.

# Then why not calling it FireLoop?
Because first of all it won't be built on top of LoopBack, and second because it won't imitate the FireBase API.

The new project is RPC/MicroServices oriented and is built from scratch with almost zero dependencies and with its own `Service Oriented Architecture` implementation providing a `Remote Call Procedure` API for communication between these services.

And for that reason, this new project is unable to be called FireLoop.

# Will my current FireLoop apps work on this new Project?
Unfortunately, it won't work on this new project, nor on LB4. And that is one of the reasons I'm starting this new project because I simply must not delegate the stability of my project to others.

# This project... What is going to have in common with FireLoop?
First is built on TypeScript but now, it will also be compatible with plain JS projects (for those hatin' TS)

Second, it will provide client SDK but this time won't be Angular specific but it will be compatible with any JavaScript front-end framework, even in plain JavaScript projects.

# It will continue using socket.io/websocket as transportation?
I'm also leaving socket.io and this new project is being built using EventStreams and gRPC.

# Is this new project an actual MicroServices platform or just another REST API Services framework
Of course, this is a true SOA project, each app / service runs on separated processes and communication between these services and clients can be done through the provided Remote Procedure Call (RPC) API.

Therefore if any of your apps crash, the rest of the loaded applications will remain up and running, then the server will try to start your crashed app again.

# It sounds like there is already some progress with this.
Yes, that is the reason I'm publishing this final announcement.

# When can we know more details?
FireLoop is done from now and so on, no more details will be communicated on that.

About the new project, we already have a very good progress and we even have a name, but will be posting details about it once we do some branding.

Thanks to all for your support on this project. I don't really want to say that this project is dead.

It is just a re-born as a new project but now with its own personality.

Cheers
Jon

**Comment by JonnyBGod** [comment]
Cool, I would pretty mush like to follow it and maybe contribute.
I totally get your point, thought about that several time now too. One needs some guts and time to go for a new framework though.

Good luck with the new project. And let me know when I can have a glance at it.

**Comment by jonathan-casarrubias** [comment]
Hey @JonnyBGod thanks, I did expect you to be the first one in response since you and I started working together on the SDK at the same time a while ago.

Yeah I know that feel has been around many of us for a while, I will be posting more about this new project soon, I want my first commit to be entirely tested. But I'll share a sneak peak now

![image](https://user-images.githubusercontent.com/1533239/36065421-2a0f48f8-0e60-11e8-809f-5d1fb2201dba.png)

![image](https://user-images.githubusercontent.com/1533239/36065377-72340584-0e5f-11e8-8b46-a160d5ac0a65.png)

Once I publish the first commit I would really appreciate for core contributors.

Cheers!
Jon

**Comment by Nosfistis** [comment]
Bummer to hear that the support is dropped for the fireloop project array, but good luck on your new one. I'm actually interested to see your new project out.

**Comment by beeman** [comment]
Hey Jon, 

Thanks for the clear explanation on why you are terminating support. I fully understand it, hopefully the current versions will keep working for a bit while I migrate my projects away from it.

Really looking forward to your new project.

Hope to talk soon, Cheers!

**Comment by certifirm** [comment]
Really bad news for the comunity.  

Thanks a lot for your explanation.  I will follow you on your new projects.  And thanks for all your contributions to Loopback.

**Comment by dmastag** [comment]
@jonathan-casarrubias thanks for all your contributions to the community.
This comes as a shock since I have grown dependent on your modules and its actually the biggest reason why i have stayed on Loopback.

Good Luck on your framework, will definitely keep an eye on it!

**Comment by certifirm** [comment]
Must we understand that loopback-component-realtime and loopback-sdk-builder for LB3 are out of maintanance too?

**Comment by brannon-darby** [comment]
@jonathan-casarrubias - looking forward to the next one, brother.  let me know if there's anything i can do to help.

**Comment by jeremyadoux** [comment]
@jonathan-casarrubias Thank for all your work.

What backend framework do you use, if not loopback ? And what do you think about LB4 ?

Thx

**Comment by jonathan-casarrubias** [comment]
Hey guys thanks for your nice words, I'm glad you understand and are even interested in the new project.

I'm trying to solve some problems that I don't think any other framework is doing right now, though there are many other cool options out there like Nest I still believe I have something cool to offer.

Anyway I will provide more details once we launch the new site.

Cheers
Jon

**Comment by jonathan-casarrubias** [comment]
Hi Guys, anyone interested in the new project I'm starting to document it for you to start playing with it.

I really regret I didn't start FireLoop from scratch instead of building it on top of LoopBack as I did, but that helped many of you know this project and me to learn a lot of lessons, so I hope that now that I'm free to architect as I consider is best, I'm really hoping you guys to give it a chance and maybe consider to migrate when the framework is ready.

Also, since OnixJS is compatible with any DataSource, so you guys are free to install the LoopBack DataSource Juggler and easily migrate to OnixJS.

With the current information I have I'm able to think that it will be easier to migrate from FireLoop -> OnixJS than LB3 -> LB4.

Regards,
Jon

https://github.com/onixjs/core/wiki
https://github.com/onixjs/examples
