### ISSUE TITLE
Multiple emits when using 'create'

### ISSUE THREAD

**Issue by ildar-faizov** [mean-expert-official/fireloop.io#139]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [x] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [x] Other

Write other if any: 1.0.0-beta.2.7

#### Please add a description for your issue:

Assume I want to create multiple objects using FireLoopRef#create and subscribe to its result.
```typescript
private ref : FireLoopRef<Entity>;
// ...
const entities = [
  new Entity('John'),
  new Entity('Sara')
];
entities.forEach((e : Entity) => {
  ref.create(e).subscribe((result : Entity) => console.log(result.id));
});
```
In the output each entity will be mentioned twice:
```
1
1
2
2
```
Is it designed to be so? For me such result is not expected. The observable that reflects creation of a certain object is notified when any object is created.

**Comment by certifirm** [comment]
Are you using Ionic, Angular, ...?  I had similar issue in Ionic, because the onReady event starts multiple times.

**Comment by ildar-faizov** [comment]
@jotae1e I'm using Angular only.

**Comment by certifirm** [comment]
Another question.  Are you using authentication?

https://github.com/mean-expert-official/fireloop.io/wiki/Authentication

Can you test if when you go out of the page and then reenter to the same page, WITHOUT reload the app, have you one plus result?

Like: 
1
1
1
2
2
2

**Comment by ildar-faizov** [comment]
@jotae1e no, I'm not using authentication. It is disabled in configs. The code from my example is not from loading scenario. It is a simple button - when clicked, it runs a loop and creates a few instances in a cycle. Not sure I fully understand how to reenter the same page without reload when there is no authentication.

Probably I can show the reason of such behavior. Here is an excerpt from FireLoopRef.ts:
```typescript
private operation(event: string, data: any): Observable<T> {
  ...
  resultEvent = `${this.model.getModelName()}.value.result.${this.id}`;
  ...
  this.socket.on(resultEvent, (res: any) => {
    if (res.error) {
      subject.error(res);
    } else {
      subject.next(res);
    }
  });  
}
```
The resulting subject subscribes for an event. But an event identifier does not contain any info to be matched against an entity created. It will receive all creation events until completed. Therefore when I create two instances immediately one after another and subscribe independently to each observable, each of them will be notified about the other's event.

**Comment by certifirm** [comment]
I see.  Nothing to add.  May require some work to correct this bug.

**Comment by jonathan-casarrubias** [comment]
Hi guys thanks for reaching out.

Hey so, I really want to apologize for saying this but I'm stopping the support for FireLoop or any LoopBack module I built.

I'm working on a new project from scratch that of course is not built on top of LoopBack or anything else, this new project will also provide a SDK but now it won't be FrameWork specific, therefore you should be able to use it in Angular 5, React, Vue or even plain JavaScript projects


I apologize if you started a project on FireLoop, here I give a more detailed explanation:
https://github.com/mean-expert-official/fireloop.io/issues/137
