### ISSUE TITLE
Remote method and onRemote with RealTime

### ISSUE THREAD

**Issue by certifirm** [mean-expert-official/fireloop.io#140]
#### What type of issue are you creating?
- [X] Bug
- [ ] Enhancement
- [X] Question

#### What version of this module are you using?
- [X] 2.1.0-beta.n (2.1 Beta n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:
`
Loopback:

    Mensajeschats.enviarmensaje = function (usuariocont, mensaje, options, cb) {
        var userid = options.accessToken.userId

    Mensajeschats.remoteMethod('enviarmensaje', {
        http: { verb: 'post' },
        accepts: [
            { arg: 'usuariocont', type: 'number' },
            { arg: 'mensaje', type: 'string' },
            { arg: 'options', type: 'object', http: 'optionsFromRequest' }
        ],
        returns: [
            { arg: 'respuesta', type: 'object', root: true }
        ],
        description: ["Enviar mensaje"]
    })

Angular:
      this.MensajeschatsRef2.remote('enviarmensaje', [this.usuario2.id, message], true).subscribe(
        res => console.log("MENSAJE: " + JSON.stringify(res))
      )
`
Error:  
var userid = options.accessToken.userId
TypeError: Cannot read property 'userId' of undefined

If I call with:
`
this.mensajeschatsapi.enviarmensaje(this.usuario2.id, message).subscribe(
        res => console.log("MENSAJE: " + JSON.stringify(res))
)
`
Works well

Its like context options are not accessible if you call a method with remote

Thanks

**Comment by jonathan-casarrubias** [comment]
Hi @totalard thanks for reaching out.

Hey so, I really want to apologize for saying this but I'm stopping the support for FireLoop or any LoopBack module I built.

I'm working on a new project from scratch that of course is not built on top of LoopBack or anything else, this new project will also provide a SDK but now it won't be FrameWork specific, therefore you should be able to use it in Angular 5, React, Vue or even plain JavaScript projects


I apologize if you started a project on FireLoop, here I give a more detailed explanation:
https://github.com/mean-expert-official/fireloop.io/issues/137
