### ISSUE TITLE
onReady runs multiple times

### ISSUE THREAD

**Issue by certifirm** [mean-expert-official/fireloop.io#141]
#### What type of issue are you creating?
- [X] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [X] 2.1.0-beta.n (2.1 Beta n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

I am using Ionic with Loopback with the realtime-component.  

I have one Module with the code of authentificacion:

`
ngOnInit() {
    if (
      this.realTime.connection.isConnected() &&
      this.realTime.connection.authenticated
    ) {
      this.realTime.onReady().subscribe(() => this.setup());
    } else {
      this.realTime.onAuthenticated().subscribe(() => this.setup());
      this.realTime.onReady().subscribe();
    }
  }
`

If I close the module and then reenter, the onReady event executes multiple times. My solution (WORKAROUND) is put the realtime in a Service, and then, call this reference from the components, to the same object.  

If not, each time I get the same result one time.  In the next enter, two times, etc...

I used the authentication tutorial, but may be that the example works but it's not correct.

**Comment by jonathan-casarrubias** [comment]
Hi @jotae1e thanks for reaching out.

Hey so, I really want to apologize for saying this but I'm stopping the support for FireLoop or any LoopBack module I built.

I'm working on a new project from scratch that of course is not built on top of LoopBack or anything else, this new project will also provide a SDK but now it won't be FrameWork specific, therefore you should be able to use it in Angular 5, React, Vue or even plain JavaScript projects


I apologize if you started a project on FireLoop, here I give a more detailed explanation:
https://github.com/mean-expert-official/fireloop.io/issues/137
