### ISSUE TITLE
Any Upgrade to angular 5?

### ISSUE THREAD

**Issue by totalard** [mean-expert-official/fireloop.io#142]
#### What type of issue are you creating?
- [ ] Bug
- [-] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [ ] Other

Write other if any:

Kinldy Upgrade to Latest Angular 5

**Comment by jonathan-casarrubias** [comment]
Hi @totalard thanks for reaching out.

Hey so, I really want to apologize for saying this but I'm stopping the support for FireLoop or any LoopBack module I built.

I'm working on a new project from scratch that of course is not built on top of LoopBack or anything else, this new project will also provide a SDK but now it won't be FrameWork specific, therefore you should be able to use it in Angular 5, React, Vue or even plain JavaScript projects


I apologize if you started a project on FireLoop, here I give a more detailed explanation:
https://github.com/mean-expert-official/fireloop.io/issues/137

Cheers Jon
