### ISSUE TITLE
Fireloop docs now point to onixjs

### ISSUE THREAD

**Issue by aitorllj93** [mean-expert-official/fireloop.io#143]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [x] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

Fireloop docs now point to onixjs. [Check it](http://docs.fireloop.io/).

Do you know any good alternative for WebSockets on Loopback 3?

**Comment by jonathan-casarrubias** [comment]
@aitorllj93 thanks for reaching out, hey so... Here I explain the reasons:

https://www.npmjs.com/package/@mean-expert/loopback-sdk-builder#official-communication

Though I'm not personally supporting any of the LB modules anymore, the SDK and RealTime components will remain up and updated as long as the community send patches.

Anyway, none of these modules will work by the moment LB4 is released.

Cheers
Jon
