### ISSUE TITLE
Loopback v3 support

### ISSUE THREAD

**Issue by John0x** [mean-expert-official/fireloop.io#18]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [x] Question
#### What version of this module are you using?

Newest from npm
#### Please add a description for your issue:

Just wondering whether or not fireloop currently supports the pre-release version of loopback v3?

**Comment by jonathan-casarrubias** [comment]
@John0x yes it does, but lets break into parts.

1.- The fireloop server is almost 100% loopback but for the mean-experts's modules and models in typescript, so whatever that works in a regular loopback v3 app, should work here.

2.- The SDK Builder already implements a fix to create the SDK for both, version 2 and 3.... Though I verified a couple of months ago, no body added a bug for it.

Cheers
Jon
