### ISSUE TITLE
Define Models declaratively in TypeScript via Decorators

### ISSUE THREAD

**Issue by vwchu** [mean-expert-official/fireloop.io#24]
#### What type of issue are you creating?
- [ ] Bug
- [x] Enhancement
- [ ] Question

#### What version of this module are you using?
Fireloop Alpha 36

#### Please add a description for your issue:

In addition to generating TypeScript Models, it would be incredibly useful and significant improve the usability if the models could be define declaratively completely within TypeScript using Decorators in lieu of using JSON files. For instance:

```ts

@Model({
   dataSource: "db",
   ...
})
class Author {

   @Property({ required: true })
   firstName: string;
   ...
}
```

The Decorator could simply be wrappers or facade over the existing APIs:

```js
loopback.createModel({
  name: 'Author',
  properties: {
    firstName: 'string',
    required: true,
    ...
  },
  ...
});
```

**Comment by jonathan-casarrubias** [comment]
Hey @vwchu that is such a great idea.

I need to fix any new issue created after the SDK builder RC breaking changes, but I will definitely consider this improvement really soon.

**Comment by jonathan-casarrubias** [comment]
I'm updating this repository structure to keep all of the modules in one place, it will be much easier to track for everyone, though I will still publish them in NPM as separated modules.

https://github.com/mean-expert-official/fireloop.io/tree/master/decorators

That is the directory for decorators and will be adding features like the requested in here.

cheers
Jon

**Comment by jonathan-casarrubias** [comment]
Hi @vwchu 

Hey so, I really want to apologize for saying this but I'm stopping the support for FireLoop or any LoopBack module I built.

I'm working on a new project from scratch that of course is not built on top of LoopBack or anything else, this new project will also provide a SDK but now it won't be FrameWork specific, therefore you should be able to use it in Angular 5, React, Vue or even plain JavaScript projects


I apologize if you started a project on FireLoop, here I give a more detailed explanation:
https://github.com/mean-expert-official/fireloop.io/issues/137
