### ISSUE TITLE
Fail to generate Angular2 client

### ISSUE THREAD

**Issue by james-lau** [mean-expert-official/fireloop.io#26]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
FireLoop Version: 1.0.0-alpha.36

#### Please add a description for your issue:
When running the "Generate Angular2 Client" option, the following error appear
[errorlog.txt](https://github.com/mean-expert-official/fireloop.io/files/646073/errorlog.txt)

**Comment by jonathan-casarrubias** [comment]
Hey @james-lau thanks for reporting, there is a new SDK Builder version and I believe it broke the process of generating an app.

I will verify and send a fix ASAP.

Cheers
Jon

**Comment by yagobski** [comment]
any update?

**Comment by jonathan-casarrubias** [comment]
Hi @yagobski thanks for reaching out,

Hey so yes... The SDK Builder has been fixed, I have been fixing also anything related to building apps and sdks for NativeScript using the FireLoop CLI..

I estimate that by the following couple of days I will be publishing a fixed version for web apps.

Cheers
Jon

**Comment by jonathan-casarrubias** [comment]
~~Ok some issues presented on the SDK needed my attention... But yesterday launched the RC 6 and now I'm focusing on fixing all of this.~~

I have been working on this but I was unable to replicate the exact issue, thought I had to fix other issues related to the SDK Builder updates.

Analyzing the stack you posted here, I see you are in windows, I'm wondering if you both are in windows machine? I have had issues not managing well the filesystem, if it is the case I will try to test in a win machine and see if I can replicate there.

Anyway, for me in mac is now working, if you upgrade to alpha.38 and confirm the issue still persist I can go deeper on this issue.

Cheers
Jon
