### ISSUE TITLE
Add FireLoop Dedicated Documentation

### ISSUE THREAD

**Issue by jonathan-casarrubias** [mean-expert-official/fireloop.io#3]

**Comment by Nosfistis** [comment]
Is [fireloop.io](fireloop.io) down?

**Comment by jonathan-casarrubias** [comment]
Hey @Miced thanks for reaching out...

Yes we are having some troubles here, I have 1 expired CC and I need the replacement, and a Lost the other one... so unfortunately I'm unable to pay the service until I fix the problem with the bank.

I'm sorry for the issue, I'll try to fix this asap..

Cheers
Jon
