### ISSUE TITLE
Support for LoopBack V3

### ISSUE THREAD

**Issue by ellipizle** [mean-expert-official/fireloop.io#43]
#### What type of issue are you creating?
- [ ] Bug
- [x] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] Release 1.0.0-beta.1.3
- [ ] Other

Write other if any:

#### Please add a description for your issue:

I am using this version of fireloop (Release 1.0.0-beta.1.3) .
new i issue this command `fireloop`
After selecting Generate Fireloop Project, it skipped the regular flow of
`
? What\'s the name of your application? fireloop_project
? Which version of LoopBack would you like to use? 2.x (stable)
? What kind of application do you have in mind? api-server (A LoopBack API server with local User auth)
` 
and it just goes straight to `Setting up your new fireloop environment` and creates the project without giving me the chance to set the name of the project and version of loopback

**Comment by brannon-darby** [comment]
hi @Ellipizle 

FireLoop currently only supports LoopBack v2, as there are issues to solve with v3 before we can support it.  v3 will be supported once those issues are resolved.

**Comment by jonathan-casarrubias** [comment]
Note: This may also require modifications within the SDK Builder to support V3, not totally sure this will be on beta.2 but I will add the label anyway.

**Comment by ptesar-xyndata** [comment]
Hello, in Readme it's written that loopback v3 is supported. is it really supported in 1.0.0-beta.1.3?
Thx

**Comment by brannon-darby** [comment]
@Ellipizle @PatrikTes 

The latest release of FireLoop (1.0.0-beta.2.3) and the SDK Builder includes support for LoopBack 3.  Check it out and let us know if there are any issues!
