### ISSUE TITLE
server-side model changes do not result in a change event on the client

### ISSUE THREAD

**Issue by wvlancke** [mean-expert-official/fireloop.io#46]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [x ] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [x ] Other 

Write other if any:
1.0.0-beta.1.3

#### Please add a description for your issue:
I've set up a basic project with one model (called Job) and an Angular2 client application.
Everything is working as expected when I perform operations (create/delete/update) in the client application. 
However, when I update the same object on the server using Job.updateOrCreate, no message is received in the client application. Do I have to configure the server (loopback 3) further, or do I need to create a fireloop client on the server and perform all model operations through that client? And, if so, how do I create a fireloop client in the loopback server?

**Comment by jonathan-casarrubias** [comment]
Hi @wvlancke thanks for reaching out,

Hey so this is a very good point, currently we have just leave the client side in angular stable, so I'm pretty sure anything you do from the front-end will work.

But I'm still deciding, how to handle this in the backend I'm thinking in programmatically adding hooks to notify clients when something has been added, updated or removed in the backend.

So my idea is that at the end, you should be able to use backend methods like, updateOrCreate directly and the real-time module should automatically notify, fireloop clients.

Anyway this will be published during the next beta releases, pretty sure will be before any Release Candidate.

Cheers
Jon

**Comment by davexs2020** [comment]
+1, can loopback-sdk-builder / IO Module (new)  implement this feature? Thanks

**Comment by jonathan-casarrubias** [comment]
This is already implemented, 

please take a look on this issue: https://github.com/mean-expert-official/loopback-component-realtime/issues/38
