### ISSUE TITLE
Error before finishing the Project generation

### ISSUE THREAD

**Issue by request-eduardo** [mean-expert-official/fireloop.io#56]
#### What type of issue are you creating?
- [X] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [X] Other

Write other if any:
FireLoop Version: 1.0.0-beta.1.3

#### Please add a description for your issue:

I run the fireloop command, and after a while I get an error. Here is my terminal log

➜  fireloop_project fireloop

     _-----_     ╭──────────────────────────╮
    |       |    │   Welcome to FireLoop!   │
    |--(o)--|    │  The MEAN Stack Platform │
   `---------´   │      by MEAN Expert      │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? What do you want to do? Generate Angular2 Client
? What type of Angular 2 Application do you want to create? Angular 2 for Web
? What's the name of your application? webapp

Creating new Angular 2 Application: webapp
installing ng2
  create .editorconfig
  create README.md
  create src/app/app.component.css
  create src/app/app.component.html
  create src/app/app.component.spec.ts
  create src/app/app.component.ts
  create src/app/app.module.ts
  create src/assets/.gitkeep
  create src/environments/environment.prod.ts
  create src/environments/environment.ts
  create src/favicon.ico
  create src/index.html
  create src/main.ts
  create src/polyfills.ts
  create src/styles.css
  create src/test.ts
  create src/tsconfig.json
  create angular-cli.json
  create e2e/app.e2e-spec.ts
  create e2e/app.po.ts
  create e2e/tsconfig.json
  create .gitignore
  create karma.conf.js
  create package.json
  create protractor.conf.js
  create tslint.json
Successfully initialized git.
Installing packages for tooling via npm.
Installed packages for tooling via npm.

     _-----_     
    |       |    ╭──────────────────────────╮
    |--(o)--|    │  Building your FireLoop  │
   `---------´   │           SDK!           │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

Generating: webapp/src/app/app.module.ts
Generating: webapp/src/tsconfig.json
Generating: webapp/src/typings.d.ts
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /bin/sh ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by request-eduardo** [comment]
After just retrying the same command, without deleting the previously (incomplete) project directory, I get the following:

➜  fireloop_project fireloop                                                

     _-----_     ╭──────────────────────────╮
    |       |    │   Welcome to FireLoop!   │
    |--(o)--|    │  The MEAN Stack Platform │
   `---------´   │      by MEAN Expert      │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? What do you want to do? Generate Angular2 Client
? What type of Angular 2 Application do you want to create? Angular 2 for Web
? What's the name of your application? webapp


Creating new Angular 2 Application: webapp
Directory 'webapp' already exists.

Application Status Code: 1

events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at child.Base.destinationPath (/home/eduardo/.nvm/versions/node/v6.9.1/lib/node_modules/@mean-expert/fireloop/node_modules/yeoman-generator/lib/base.js:752:28)
    at child.install (/home/eduardo/.nvm/versions/node/v6.9.1/lib/node_modules/@mean-expert/fireloop/node_modules/generator-fireloop/generators/ng2web/index.js:71:25)
    at Object.<anonymous> (/home/eduardo/.nvm/versions/node/v6.9.1/lib/node_modules/@mean-expert/fireloop/node_modules/yeoman-generator/lib/base.js:439:23)
    at /home/eduardo/.nvm/versions/node/v6.9.1/lib/node_modules/@mean-expert/fireloop/node_modules/yeoman-generator/node_modules/run-async/index.js:25:25
    at /home/eduardo/.nvm/versions/node/v6.9.1/lib/node_modules/@mean-expert/fireloop/node_modules/yeoman-generator/node_modules/run-async/index.js:24:19
    at /home/eduardo/.nvm/versions/node/v6.9.1/lib/node_modules/@mean-expert/fireloop/node_modules/yeoman-generator/lib/base.js:440:9
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)

**Comment by jonathan-casarrubias** [comment]
OK I see it is like a corrupted client problem, once corrupted there is no obvious way to clean it up.

**Comment by jonathan-casarrubias** [comment]
This issue has should be fixed on beta 2.3
