### ISSUE TITLE
How to Broadcast Data From Server Side

### ISSUE THREAD

**Issue by rajweb** [mean-expert-official/fireloop.io#57]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [*] Question

#### What version of this module are you using?
- [*] 2.1.0-beta.n (2.1 Beta n)
- [ ] Other

Write other if any:

Hello,
i am new in loopback/mean.expert and try to broadcast data from server side. on client side fileloop realtime data sycroniztion work fine. but i require to broadcast data from server side (eg. take BTC rate from other website on server/api and broadcast it to our client).

i am try using it by NEW IO Module Example but it not works. tested code given below:

**Server Side Code**

`module.exports = function (app) { 
       app.on('started', function () { 
              app.mx.IO.emit('test', 'Hello World'); 
        }); 
  };`

**Client Side Code**

```
import { Component, OnInit } from '@angular/core';
import { RealTime } from '../shared/sdk/services';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  constructor(private realTime: RealTime) {  this.realTime.IO.emit('test', 'hello publish it');
  	 this.realTime.IO.emit('test', 'raj angular');
     this.realTime.IO.on('test').subscribe((msg: any) => console.log('Realtime Cli Msg ='+ msg));
  }

  ngOnInit() {
  }

}

```

above code is not working. so please provide me solution for server side broadcasting.

Is it works on your system or not?
#### Please add a description for your issue:

**Comment by jonathan-casarrubias** [comment]
Hi @rajweb thanks for reaching me out, I will verify your use case and come up with an advice for you.

Cheers
Jon

**Comment by rajweb** [comment]
Thanks boss....I am waiting for advice.

**Comment by mikkoh85** [comment]
Heads Up @rajweb. I got this working. Today I will put the code here, but now, I'm in a hurry. Catch you later :)

**Comment by mikkoh85** [comment]
I used FireLoop server and Angular 2 generated with `fireloop` cli command. I had to change that server side code to use TypeScript. In your example you are using plain JavaScript syntax and FireLoop uses (at least now) TypeScript. 

So.. I made file connected.ts into `/fireloop/server/boot/` folder (you can name it whatever you like) and put this code inside of it:

```
import { BootScript } from '@mean-expert/boot-script';

@BootScript()
class Connected {
    constructor(app: any) {
        app.on('started', function () {
            app.mx.IO.on("test1", function(msg: string) {
                console.log("test1:", msg);
                app.mx.IO.emit('test2', 'Hello World');   
            });
        }); 
    }
}

module.exports = Connected;
```

On client side in app.component.ts I have following constructor:

```
constructor(private rt: RealTime) {
    this.rt.onReady().subscribe(() => {
      this.rt.IO.on('test2').subscribe((msg: any) => console.log('test2:', msg));
      this.rt.IO.emit('test1', 'raj angular');
    });
}
```

So, it sould work both ways.

**Comment by rajweb** [comment]
thanx for reply... it works
