### ISSUE TITLE
The fireloop directory should be configurable

### ISSUE THREAD

**Issue by beeman** [mean-expert-official/fireloop.io#59]
#### What type of issue are you creating?
- [ ] Bug
- [x] Enhancement
- [ ] Question

#### What version of this module are you using?
- [x] 2.1.0-beta.n (2.1 Beta n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

The directory that is used to install the fireloop server component (`./fireloop`) should be made configurable just like the directory for the Angular client app.

While the default is fine, there are use cases where people want to have the ability to change this for whatever reason. For instance, in my project I prefer using `api` and `admin` instead for `fireloop` and `webapp`. 

I'm happy to create a PR to add support for this, this issue is to start the discussion and track progress.

**Comment by jonathan-casarrubias** [comment]
@beeman thats fine I don't see an  issue on that, if a dev user wants to change the directory name it should be able to do it.

The pull request will be much appreciated :)

**Comment by jonathan-casarrubias** [comment]
@beeman forget about the PR... I already implemented this feature... will be landed on the next version
