### ISSUE TITLE
remote method returning Promise not supported

### ISSUE THREAD

**Issue by masterclock** [mean-expert-official/fireloop.io#60]
#### What type of issue are you creating?
- [ ] Bug
- [x ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] "@mean-expert/model": "1.0.9",
- [ ] "@mean-export/model-register": "1.0.5"

https://github.com/mean-expert-official/model-register/blob/master/index.ts#L33

the wrapper function does not return value, adding a `return` solves the problem

**Comment by jonathan-casarrubias** [comment]
ok cool @masterclock thanks for reporting I will be adding it to the next version
