### ISSUE TITLE
instance remote method not supported

### ISSUE THREAD

**Issue by masterclock** [mean-expert-official/fireloop.io#61]
#### What type of issue are you creating?
- [ ] Bug
- [ x] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ]  "@mean-expert/model": "1.0.9",
- [ ]  "@mean-export/model-register": "1.0.5"

#### Please add a description for your issue:
instance remote method, i.e. method name startsWith 'prototype.' results runtime error

**Comment by jonathan-casarrubias** [comment]
Hi @masterclock thanks for reaching out, I'm not totally sure about the issue.

Would you mind to add an example of it?

**Comment by beeman** [comment]
This is most likely in LoopBack v3. A non-static remote method will be defined like this: 

```json
 "prototype.buy": {
      "accepts": [
        {
          "arg": "quantity",
          "type": "number",
          "required": true,
          "description": "Number of products to buy"
        }
      ],
      "returns": [
        {
          "arg": "result",
          "type": "object",
          "root": true,
          "description": "The result of the purchase"
        }
      ],
      "description": "Buy this product",
      "http": [
        {
          "path": "/buy",
          "verb": "post"
        }
      ]
    }
```

**Comment by Nosfistis** [comment]
I tried to add the definition this way, while also adding in constructor:
```
constructor(public model: any) {
    model.prototype.buy = this.buy;
}

buy(next: Function): void {
    console.log(this);
    next(null);
} 
```
to link the class function to the instance method. It works and the log prints the instance object (since this does not refer to the class anymore) but it gives TS errors when trying to access the object properties (such as id). Also, accessing the class model/application via this.constructor gives TS errors again.

Any better way to deal with this?

**Comment by jonathan-casarrubias** [comment]
Hi guys

Hey so, I really want to apologize for saying this but I'm stopping the support for FireLoop or any LoopBack module I built.

I'm working on a new project from scratch that of course is not built on top of LoopBack or anything else, this new project will also provide a SDK but now it won't be FrameWork specific, therefore you should be able to use it in Angular 5, React, Vue or even plain JavaScript projects


I apologize if you started a project on FireLoop, here I give a more detailed explanation:
https://github.com/mean-expert-official/fireloop.io/issues/137

**Comment by davidpestana** [comment]
Hi guys...

i can solve it using a hibrid solution

1/ create a boot/script in server folder using javascript... not Typescript

![captura de pantalla de 2018-02-23 14-13-47](https://user-images.githubusercontent.com/5878617/36595764-cd4e622c-18a3-11e8-9844-58bb77a87bac.png)

2/ prototype your methods here

```
'use strict';

let loopback = require('loopback');

module.exports = function (app) {
  let YourModel = app.models.YourModel;
  YourModel.prototype.NewMethod = function (cb){
      console.log(this);
       cb(null,'yeah!');
  }
}
```
