### ISSUE TITLE
Room Model not present when Creating Client SDK

### ISSUE THREAD

**Issue by jasondbchapman** [mean-expert-official/fireloop.io#62]
#### What type of issue are you creating?
- [x ] Question

#### What version of this module are you using?
- [x] 2.1.0-beta.n (2.1 Beta n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:
Attempting to follow this tutorial; however, the **Room model is not found** and it is not installed when I create the client SDK.  

**These two questions never occur when I am creating the client SDK:** 
? What SDK features do you want to include?
 (*) Enable PubSub + IO + FireLoop functionality
>(*) Add default values in models
? Do you want to generate ONLY FireLoop SDK + Auth Services? (Y/n)

Thank you for your help!

**Comment by jonathan-casarrubias** [comment]
Hey @jasondbchapman thanks for reporting.

Also, I'm sorry for the late response I have had some delays, but I'm here to answer now..

Anyway, there were many changes in the SDK Builder that broke the FireLoop CLI, I will be upgrading the CLI Asap

Regards
