### ISSUE TITLE
Combined web client and mobile client

### ISSUE THREAD

**Issue by WhatzzUp** [mean-expert-official/fireloop.io#63]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [x] Question

#### What version of this module are you using?
- [x] 1.0.0-beta.1.3 (1.0.0 Beta 1.3)
- [ ] Other

Write other if any:

#### Please add a description for your issue:
Hey mean-expert Team,

actually a build prototype with fireloop and the web client and now i want to add the NativeScript to build an native app, with the original code of my prototpye...

Is there exist an example how to use fireloop combined with web client and mobile client (nativeScript)?
My goal is to develop the code only once and then as a webapp and as a native app to provide.
Is it possible at all?

Sorry for my language... ;-)

Fireloop is amazing <3

**Comment by jonathan-casarrubias** [comment]
@WhatzzUp thanks for reaching out.

First of all sorry for the late response, I had some delays with a project and the team has been working hard with the fireloop starter, so sorry again for the late response.

Hey so, I really would not recommend you to completely share the code between the web and nativescript app, unless you talk about services or pipes, but in my personal experience, you will load a ton of plugins environment specific that will make you pass a hard time.


My recommendation: Bundle in NgModules whatever you can share between your apps, and anything related to UI or plugins will be app specific.

So you will really have 2 applications, but you can share the ng modules as I just recommended.

I hope this information helps you on your project.

Cheers
Jon

**Comment by WhatzzUp** [comment]
Hi jon,

thx for the answer. Helped me a lot! :)

Greezzze
chris
