### ISSUE TITLE
NativeScript Error

### ISSUE THREAD

**Issue by ProofWoW** [mean-expert-official/fireloop.io#64]
#### What type of issue are you creating?
- [+ ] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ +] 1.0.0-beta.1.3 (1.0.0 Beta 1.3)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

Hello.
I have generated nativescript client for fireloop
But cant run.
When i run "fireloop serve" and choice serverside and clientside
Me give error:

events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'cmd' of undefined

**Comment by jonathan-casarrubias** [comment]
@ProofWoW thanks for reporting, for now I recommend you to run the FireLoop Server and the NativeScript app separately.

Load FireLoop server by using fireloop serve, and for now load the nativescript app by using tns run.

I had some delays that didn't allow me to finish the nativescript integration, but it will be fixed asap.

Regards
Jon
