### ISSUE TITLE
Missing dependency wcwidth

### ISSUE THREAD

**Issue by pekosoG** [mean-expert-official/fireloop.io#65]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [ x ] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [ x ] Other

Write other if any:
FireLoop Version: 1.0.0-beta.1.3 (Fresh install from NPM)
 
#### Please add a description for your issue:
Is there an missing step on the readme here at this repo or on the installation process?

I had to install in my machine the "wcwidth" library in order to initialize the wizard.

**Comment by jonathan-casarrubias** [comment]
@pekosoG thanks for reaching out.

Hey so, not sure about this missing dependency... I haven't personally seen, nor anyone have complained about that specific dependency.

But I can say that sometimes there are connection issues that won't allow to correctly install a specific library.

If that is the case, this should be fixed just by trying a clean installation of the platform and see if the problem persist.

Cheers
Jon
