### ISSUE TITLE
Changing the listening address for the ng2 App

### ISSUE THREAD

**Issue by juantoledo** [mean-expert-official/fireloop.io#66]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [X] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [X] Other

Write other if any:

#### Please add a description for your issue:

Hello, 

Is there any easy  way to configure the listening address of the Angular 2 App, from localhost:4200 to 0.0.0.0:4200 ? 

Thanks in advance

J

**Comment by brannon-darby** [comment]
hi @juantoledo 

fireloop leverages @angular/cli to serve the angular app in dev mode.  please refer to the @angular/cli documentation to accomplish this.

https://github.com/angular/angular-cli#usage

> You can configure the default HTTP host and port used by the development server with two command line options :

`ng serve --host 0.0.0.0 --port 4201`

**Comment by brannon-darby** [comment]
@juantoledo - if you can join our slack group, i'll be happy to help you out with this.  feel free to shoot me a message if you need any help.
