### ISSUE TITLE
Implement path.sep to get custom directory name 

### ISSUE THREAD

**Issue by jonathan-casarrubias** [mean-expert-official/fireloop.io#69]
#### What type of issue are you creating?
- [X] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [X] 2.1.0-beta.n (2.1 Beta n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

There is a problem generating projects in Beta 3, where in windows environments we are not getting the API directory name.

Use path.sep will fix the issue regardless the environment

**Comment by brannon-darby** [comment]
@jonathan-casarrubias - i was able to test this successfully on my windows machine.

reference:

```let apiName: string = this.destinationPath().split(path.sep).pop();```
