### ISSUE TITLE
Mysql fulltext query with fireloop *Question*

### ISSUE THREAD

**Issue by WhatzzUp** [mean-expert-official/fireloop.io#71]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [x] Question

#### What version of this module are you using?
- [x] 2.1.0-beta.n (2.1 Beta n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

The following example shows, how i can querying data with the built in LoopBack Query Language:
```
constructor(private realTime: RealTime) {
    this.realTime
        .onReady()
        .subscribe(() =>
            this.RoomReference = this.realTime.FireLoop.ref<Room>(Room)
            this.RoomReference.on('change',{
              limit: 10,
              order: 'id DESC',
              include: 'members'
            }).subscribe((rooms: Room[]) => console.log(rooms));
        );
  }
```
This works wunderfull!

Now i would like to create a fulltext (match against) query and i found this example:

[https://github.com/strongloop/loopback/issues/615](url)
```
var mySQLDataSource = app.dataSources.mysql;
var mySQLPool = mySQLDataSource.connector.client;
mySQLPool.query('SELECT * FROM TABLE WHERE MATCH(title, body) AGAINST (\'LOOPBACK\')', function(err, rows, fields) {
  if (err) throw err;
  ...
});
```
Any idea how I can realize a "native" fulltext query, with fireloop and the mysql driver?
Sorry for my language :)

Cheers

Christian

**Comment by jonathan-casarrubias** [comment]
Hi @WhatzzUp thanks for reaching out..

Hey so as you can see, the juggled does not provide support for the match feature, so literally we can not do anything in our side.

But in some uses cases, it might worth something to create a custom remote method and then listen that remote method.

The problem though is that won't work as the 'Change' method, the only way your listeners will be fired is b  calling the method, it can be done from the current or from another client.

Lets suppose:

1.- ClientA -----> subscribes ----> Custom remote method

2.- ClientB ----> calls -----> Custom remote method

3.- ClientA ----> get notification that ClientB called custom remote method.

That is a different pattern, and not totally sure is what you are looking for though.

I hope this information helps you clarify your question

**Comment by brannon-darby** [comment]
@WhatzzUp 

addding to the comments from @jonathan-casarrubias - if your goal is simply to leverage a mysql datasource, you should check out the mysql-connector.

http://loopback.io/doc/en/lb3/MySQL-connector.html

**Comment by WhatzzUp** [comment]
@jonathan-casarrubias, @brannon-darby 

Thank you for the fast reply.

I would like to implement a fulltext search for our customers, to get searched projects in a list. 

We started with a normal **LIKE '%value%'** query,which works fine with fireloop and the mysql connector. The problem with the LIKE query is, that a medium-sized data set of up to 10,000 records (500,000 words) or so, **LIKE** only takes a fraction of a second, but our tables are up to 10M Records and thats the **dead** for an **LIKE** query. 

So we decidet to use the fulltext index and realize the search with "match ... against()". But to use the **"match against**" query we must use the query according to this issue [https://github.com/strongloop/loopback/issues/615](url)

I hope i could descripe the current situation.

I will check out the mysql-connector again, @brannon-darby thank you :) and i will try your idea @jonathan-casarrubias 

Thank you guys :)
