### ISSUE TITLE
Add an option to start all fireloop services (fireloop serve --all)

### ISSUE THREAD

**Issue by beeman** [mean-expert-official/fireloop.io#72]
#### What type of issue are you creating?
- [x] Enhancement

#### What version of this module are you using?
- [x] 1.0.0-beta.2.4

#### Please add a description for your issue:

It would be nice if one could run `fireloop serve --all` and have all detected services selected, instead of selecting them manually

<img width="787" alt="screen shot 2017-03-28 at 20 43 05" src="https://cloud.githubusercontent.com/assets/36491/24434925/ff555b74-13f7-11e7-95ea-cb1b11dbb7cf.png">

**Comment by jonathan-casarrubias** [comment]
Hi @beeman 

Hey so, I really want to apologize for saying this but I'm stopping the support for FireLoop or any LoopBack module I built.

I'm working on a new project from scratch that of course is not built on top of LoopBack or anything else, this new project will also provide a SDK but now it won't be FrameWork specific, therefore you should be able to use it in Angular 5, React, Vue or even plain JavaScript projects


I apologize if you started a project on FireLoop, here I give a more detailed explanation:
https://github.com/mean-expert-official/fireloop.io/issues/137
