### ISSUE TITLE
Generate SDK error - default SDK (webapp) is built for every client app

### ISSUE THREAD

**Issue by bitingedgemick** [mean-expert-official/fireloop.io#74]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [x] Other

Write other if any:
1.0.0-beta.2.4

#### Please add a description for your issue:

When using the Fireloop CLI command **Generate Angular2 SDK** the command line options are not being used by the Fireloop:SDK generator. No matter which _client_ is selected the SDK for the default webapp is generated.

The command line choices should be passed to the generator in an options object as **options.clientPath** and **options.clientType** but in my install the choices are actually found in **options.options.clientPath** and **options.options.clientType** respectively.

https://github.com/bitingedgemick/fireloop.io/commit/685d169d8aceb2de9b0e121223d579262f1ab0f5 shows the changes that are working for me.

The installation is on Windows 10 just in case that may be relevant to the issue.

**Comment by jonathan-casarrubias** [comment]
@bitingedgemick thanks for reporting I will verify testing with different apps and see if I can replicate in mac

**Comment by blntylmn** [comment]
Any progress on this . I am having this issue too and this make it useless for nativescript or ionic apps. (I am on a mac sierra)

**Comment by ryodeushii** [comment]
In waiting for fixes, I've just wrote **npm** scripts to generate SDKs in proper directories

**Comment by brannon-darby** [comment]
@bitingedgemick @blntylmn @ryodeushii 

this should be resolved in the latest release of FireLoop, which includes the following commit:
https://github.com/mean-expert-official/fireloop.io/pull/92/commits/d7faca8e74fca0b7ad7db8cbf6d94a216cea3750

would you please test it out and let us know?

**Comment by brannon-darby** [comment]
the latest version allows you to set the folder where the sdk will be generated for each client, along with some other clean-up around `fireloop:serve` and `fireloop:sdk`

**Comment by bitingedgemick** [comment]
@brannon-darby 

All good for me. 

Thanks.
