### ISSUE TITLE
License

### ISSUE THREAD

**Issue by zackarychapple** [mean-expert-official/fireloop.io#76]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [x] Question

#### What version of this module are you using?
- [x] 2.1.0-beta.n (2.1 Beta n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:
Can someone please put the official license on the repo. Doing a search it seems the fireloop is MIT, but I want to make sure.

**Comment by jonathan-casarrubias** [comment]
Hey @zackarychapple thanks for reporting.

Yes every module within FireLoop is under the MIT License, I'll add the license doc within the next merge.

Cheers
Jon

**Comment by zackarychapple** [comment]
Fantastic, thank you.
