### ISSUE TITLE
Integrate GraphQL endpoint

### ISSUE THREAD

**Issue by phra** [mean-expert-official/fireloop.io#77]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [ ] Question
- [x] Feature Request

#### Please add a description for your issue:

do you have already thought about an integration with GraphQL query language? As we already have formal descriptions of our models and relationships between them i think that it wouldn't be so hard integrate it with loopback's models. Also it can probably supersede most parts of the client SDK.. maybe [apollo-client](https://github.com/apollographql/apollo-client) can be the right choice.

what do you think about this guys?

**Comment by jonathan-casarrubias** [comment]
@phra yeah we had some request for that, but in the short term I don't see that coming, though LB4 might include GraphQL support, in those terms we would be able to support it, is just I don't think that should be managed from this end, so lets see if it is implemented within LB4 and we can leverage on that

**Comment by jonathan-casarrubias** [comment]
Hi @phra 

Hey so, I really want to apologize for saying this but I'm stopping the support for FireLoop or any LoopBack module I built.

I'm working on a new project from scratch that of course is not built on top of LoopBack or anything else, this new project will also provide a SDK but now it won't be FrameWork specific, therefore you should be able to use it in Angular 5, React, Vue or even plain JavaScript projects


I apologize if you started a project on FireLoop, here I give a more detailed explanation:
https://github.com/mean-expert-official/fireloop.io/issues/137
