### ISSUE TITLE
Fireloop serve doesn't work with multiple entities anymore

### ISSUE THREAD

**Issue by mikkoh85** [mean-expert-official/fireloop.io#79]
#### What type of issue are you creating?
- [X] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [X] 1.0.0-beta.2.4
- [ ] Other

Something weird happened with `fireloop serve` cli command. First when I created the base project and then the angular 2 webapp project into it, it worked fine by selecting both projects after typing `fireloop serve`. For some reason that stopped working, it doesn't even try to start the angular project anymore. I have tried everything. I even made brand new private git repository and started all over. I tried to change the name of angular client, everything. I restarted my computer. It just doesn't start the Angular project together with fireloop anymore.

**Comment by mikkoh85** [comment]
Weird thing, I kept on hitting Enter and then it started the webapp too..

**Comment by mikkoh85** [comment]
This problem happened with Git Bash on Windows, but doesn't happen on OSX El Capitan's' bash terminal.

**Comment by jonathan-casarrubias** [comment]
hi @mikkoh85 thanks for reporting,

Hey so is that happening on a new fireloop project, or within a project created with a previous version?... There were introduced some changes that might affect older projects.

The strange part is that is only happening in git bash on windows, so it might be some platform specific problem, not sure so will need to verify

**Comment by mikkoh85** [comment]
I'll take some tests later. Now @work :)

**Comment by jonathan-casarrubias** [comment]
@mikkoh85 I have just got a confirmation about this issue from @brannon-darby, not sure why in windows is having that behavior, we'll need to either document that or see if we can workaround the issue since we leverage to yeoman that specific functionality

**Comment by mikkoh85** [comment]
ok, cool, guys :)
