### ISSUE TITLE
Realtime IO *Question*

### ISSUE THREAD

**Issue by WhatzzUp** [mean-expert-official/fireloop.io#81]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [ X] Question

#### What version of this module are you using?
- [X ] 2.1.0-beta.n (2.1 Beta n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

Hello folks,

currently im try to get deeper in fireloop and socket.io and have now a few questions.
I tried the RealtimeEngine and its AWESOME! Great job guys!

I tried to implement my own logic especially for record locking. If a client entered my ProjectComponent and modified a field, this field will be "locked" for every other client connected with this component. Actually this works fine with IO! I can´t reached this with Fireloop, i'm to less experienced with Fireloop :/ 
My current Issue is the following:
If a client is modified a field, a emit is sending to all connected devices, to lock this "field" (disable html input field). If client III is connectend while client I is modifying the field, client III get no information that this field is "modifying" because the event emit was sending before he entered the component.

Code snippets:

If a user successfuly loged in, i called 

`this.rt.onReady()`

If a client is entered my ProjectComponent, he adds a new event listener on the IO object.

`this.realTimeListener = 'project.detail.' + this.projectID`
`this.rt.IO.on(this.realTimeListener).subscribe((data: any)=> {
      this.projectJson[data.fieldname] = data.fieldProperties;
});`

- [ ] How i can get connected devices? Or the count of connected clients?
- [ ] How can i get all devices/clients which listens at the same listener?
- [ ] Can i send an "request" from a Client **to only one connected** client?
- [ ] Is this way a bad way?

I'm a beginner with socket.io and fireloop so I  hope my question is not too confusing.

Cheers

WhatzzUp

**Comment by jonathan-casarrubias** [comment]
Hi @WhatzzUp thanks for reaching out, 

Hey so, in your code snippet I don't see any FireLoop API code, but I see you are using the simple wrapper for socket.io-client. I'm clarifying this because:

a) The IO wrapper is a really basic wrapper which will provide you with the on and emit events only.
b) The FireLoop API is model oriented and not connection oriented, therefore you need to change the mentality from connection oriented mindset to model oriented mindset.

So lets take your use case as an example:

Within your `ProjectComponent` lets assume you have a field named `title`. Lets assume that `Project.title` is the field you want to lock and for this example lets assume that the project has been previously created and it has an id `12345`

Since FireLoop is model oriented,  you need to subscribe other clients to the same model reference:


````js
import { Project, FireLoopRef } from './shared/sdk/models';
import { RealTime, LoopBackAuth } from './shared/sdk/services';

@Component(...)
class ProjectComponent {

  private project: Project = new Project();
  private projectRef: FireLoopRef<Project>;

  constructor(private rt: RealtTime, private auth: LoopBackAuth) {
    this.rt.onReady().subscribe((status: string) => {
      this.projectRef = this.rt.FireLoop.ref<Project>(Project);
      this.projectRef.on('change', { where: { id: 12345 }})
                               .subscribe((project: Project) => this.project = project);
    });
  }

  lock(): void {
    if (!this.project.lockedBy) {
      this.project.lockedBy = this.auth.getCurrentUserId();
      this.projectRef.upsert(this.project).subscribe()
    } else if (this.project.lockedBy === this.auth.getCurrentUserId()) {
      // This project is already locked by me
    } else {
      // This project is locked by someone else
    }
  }

  unlock(): void {
    if (!this.project.lockedBy) {
      // This is already unlocked
    } else if (this.project.lockedBy === this.auth.getCurrentUserId()) {
      this.project.lockedBy = null;
      this.projectRef.upsert(this.project).subscribe()
    } else {
      // This is locked by someone else, can not be unlocked
    }
  }
}
```` 

and then you will manage to disable the field within your view like:

````html
<input [(ngModel)]="project.title" type="text" [disabled]="project.lockedBy && project.lockedBy !== auth.getCurrentUserId()"/>
````

I didn't test the snippets above, I just wrote that to give you an idea of how to solve that issue, just to show you that model references will be in sync with other clients and by adding a `lockedBy` property, you can lock and know who is locking that model instance.

In this case you can lock the field to any other client by defining who is locking the project and only the account that locked the field would be able to edit, even if it is in different devices... All of the devices with the same account will have the field open, while other devices with other accounts will present the field locked.

I hope this helps you clarify your questions and use case..

Regards
Jon

**Comment by WhatzzUp** [comment]
Hy @jonathan-casarrubias 
it works great! Thank you!

One point is open:
If a client has an "disconnect" (no internet connection, programm crash etc.) how can the server unlock the record?

Is it possible to use the "disconnect" handler? Or is there another "good" way?

Best Regards

Christian

**Comment by jonathan-casarrubias** [comment]
Hi @WhatzzUp I have just verified and right now there is no published way to know that, but I have just verified and it is super simple to implement though, and since I'm about to publish a new release with an important security fix, I will add a way for you to know who disconnected, it is important to notice that this will apply only for logged users, though I believe that will be fine for you...

I will add an example of what you need to do, while I publish the real-time component you can start implementing it, but it will work until you upgrade.

Create a boot script with something like:

````js
import { BootScript } from '@mean-expert/boot-script';

interface Project {
    title: string;
    lockedBy: string;
    save: Function;
}

@BootScript()
class OnDisconnect {

    constructor(protected app: any) {
        app.on('socket-disconnect', this.handler);
    }

    handler(socket: { token: { userId: string } }): void {
        this.app.models.Project.findOne({
            where: { lockedBy : socket.token.userId }, (err: Error, project: Project) => {
            if (project) {
                project.lockedBy = null;
                project.save();
            }
        })
    }
}

module.exports = OnDisconnect;

````

By doing this you will be able to unlock from the server once a socket is disconnected...

Cheers
Jon

**Comment by jonathan-casarrubias** [comment]
I just created a documentation file for this:

https://github.com/mean-expert-official/fireloop.io/wiki/Handle-Disconnections

**Comment by WhatzzUp** [comment]
Hi @jonathan-casarrubias 
thx for the fast reply!
I don´t understand your answer exactly. 
When or who is triggering the "socket-disconnect" event?
...emit("socket-disconnect"...)



Cheers
Chris

**Comment by jonathan-casarrubias** [comment]
@WhatzzUp the `socket-disconnect` event is triggered by a core component named loopback-component-realtime, that is the component that provides you all the real-time capabilities.

Internally the component knows all the people that are connected, it provides a reference for the token that the connection is using, therefore when the loopback-realtime-component detects a user has been disconnected it will trigger the event and provides you with the closed connection that includes the user token and userId.

The only thing you need to do is to create a bootscript within `server/boot/ondisconnect.ts` that will listen that event and whatever business logic you need to do in your side.

**Comment by jonathan-casarrubias** [comment]
@WhatzzUp I just published the loopback-component-realtime@1.0.0-rc.6... Update that module within the fireloop api directory.

Also I fixed an issue in the snippet I provided, the way I was getting the project didn't make sense... Basically I changed the Project call to:

````js
    handler(socket: { token: { userId: string } }): void {
        // Here we are looking for a project locked by the disconnected account
        this.app.models.Project.findOne({
            where: { lockedBy : socket.token.userId }, (err: Error, project: Project) => {
            if (project) {
                project.lockedBy = null;
                project.save();
            }
        })
    }
````

Remember that you only need to take care by creating a boot script, that is listening for the `socket-disconnect` event and then from there you can unlock the locked project.

I hope this helps you clarify your question

Cheers
Jon

**Comment by WhatzzUp** [comment]
@jonathan-casarrubias 
Thank you for your help! 
I guess i have an error or something goes wrong ... the 
> socket-disconnect
isnt triggered ... is there an extra preference to activate this? 

Thank you so much for your help Jon!

**Comment by jonathan-casarrubias** [comment]
have you updated the loopback-realtime-component already to RC6?

**Comment by WhatzzUp** [comment]
yes i have. Maybe i make something wrong :D is currently late in germany  :)

**Comment by jonathan-casarrubias** [comment]
Ok I just verified that I didn't mess up while publishing the package....

Actually it is published right, so just make sure you:

1.- **Enter the API Directory**: `$ cd to/project/fireloop` or `$ cd to/project/custom` (if you defined a custom API directory while creating the project).
2.- **Install New Dependency**: `$ npm install --save @mean-expert/loopback-component-realtime@1.0.0-rc.6`
3.- **Create BootScript**: Create a file within `fireloop/server/boot` or `custom/server/boot`, I would say `ondisconnect.ts` but the name can be whatever you want (Make sure is a .ts file)
4.- **Copy and paste the following code as it is**:

`$ vim project/fireloop/server/boot/ondisconnect.ts`
````js
import { BootScript } from '@mean-expert/boot-script';

interface Socket { token: { userId: string } }

@BootScript()
class OnDisconnect {

    constructor(public app: any) {
        app.on('socket-disconnect', (socket: Socket) => this.handler(socket));
    }

    handler(socket: Socket): void {
        if (socket.token && socket.token.userId) {
            console.log('An authenticated user has been disconnected:', socket.token.userId);
        } else {
            console.log('An anonymous user has been disconnected');
        }
    }
}

module.exports = OnDisconnect;
````

I just tested that and is working.... It would console log in the terminal, something like:

````txt
Web server listening at: http://0.0.0.0:3002
Browse your REST API at http://0.0.0.0:3002/explorer
// On refresh the browser 2 times using authenticated account
An authenticated user has been disconnected: 58f5157da22e76487f107dff
An authenticated user has been disconnected: 58f5157da22e76487f107dff
// On logged out still provides  the token 1 last time
An authenticated user has been disconnected: 58f5157da22e76487f107dff
//  Refreshed the browser 2 more times
An anonymous user has been disconnected
An anonymous user has been disconnected
````

**Comment by WhatzzUp** [comment]
@jonathan-casarrubias Good Morning,
I don't know why or how ... but now it works! Started my computer this morning .... **and it works perfectly**!

I think a little troll wanted to annoy me yesterday evening :gun:  #brainlag

Thank you so much for your help and your time! **You saved my day** 

Best regards from bavaria!
Christian

ps: I owe you a beer :beer:

**Comment by jonathan-casarrubias** [comment]
@WhatzzUp I'm glad it is now working for you, I believe you are now all set.

I hope you to build great things using FireLoop... Also, I'll be looking forward for that beer 🍺 lol...

Cheers
Jon!!

**Comment by WhatzzUp** [comment]
@jonathan-casarrubias 
The locking works perfectly, only one little point is open:
If the server is unlocking the record, i would like to send an event to all clients who listen at a specific emit event  "<tablename>.<recordID>"

Acutally the client must "refresh" the layout to recognize that the record isn't locked anymore.


This is actually the "OnDisconnect" class
```javascript

@BootScript()
class OnDisconnect {

  constructor(public app: any,public socket : any) {
    app.on('socket-disconnect', (socket: any) => this.handler(socket))
    console.log(socket)
  }

  //@desc:Unlocked records and logout disconnected users
  //@params: socket : socket => Gets the id and the token from the disconnected user
  //@result: none
  handler(socket: any): void {
    console.log(socket)
    if (socket.token && socket.token.userId) {
      console.log('An authenticated user has been disconnected:', socket.token.userId);
      this.app.models.user_activity.findOne({where: {fkey_user_id: socket.token.userId}}, (err: Error, user_activity: any) => {
        if (user_activity) {
          this.unlockField(user_activity.active_record,socket);
          user_activity.delete();
        }
      });
      this.app.models.User.logout(socket.token.id)
    } else {
      console.log('An anonymous user has been disconnected');
    }
  }

  //@desc:unlock the record in the db inclusive send an event to all clients with the same event handler
  //@params: 
  //@result: none
  private unlockField(active_record: any,socket:any) {
    console.log(active_record)
    if (active_record != "undefined" && active_record != null && active_record != "") {
      let tablename = active_record.tablename;
      let fieldname = active_record.fieldname;
      let recordID = active_record.recordID;
      let filter = {where:{id:recordID}};
      this.app.models[tablename].updateAll(filter,{lockedBy:null,lockedAt:null,lockedField:null});


    }
    socket.emit("Project.1",{lockedBy:null,lockedAt:null,lockedField:null})

  }
}

module.exports = OnDisconnect;```

Is it possible to send an emit with the socket object to all clients who listen at "Project.1"?
Is my code so okey or what can i do better?

Thx again for your time and help.

Cheers
Chris

**Comment by adechassey** [comment]
Hi guys,

Sorry to reopen this but I was searching for a way to handle user connection events.
Is there a kind of method working the same way as disconnection like **app.on('socket-authenticated')** ?

Thanks in advance,
Antoine
