### ISSUE TITLE
Error installing Angular 2 client

### ISSUE THREAD

**Issue by FishTheOriginal** [mean-expert-official/fireloop.io#83]
#### What type of issue are you creating?
- [X ] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [X ] Other

Write other if any:

#### Please add a description for your issue:
Error while trying to install Angular 2

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

node -v
v7.9.0

FireLoop Version: 1.0.0-beta.2.4

> fireloop

     _-----_     ╭──────────────────────────╮
    |       |    │   Welcome to FireLoop!   │
    |--(o)--|    │  The MEAN Stack Platform │
   `---------´   │      by MEAN Expert      │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? What do you want to do? Generate Angular2 Client
Enable NativeScript 2 Support:
$ npm install -g nativescript
Enable Ionic 2 Support:
$ npm install -g cordova ionic
? What type of Angular 2 Application do you want to create? Angular 2 for Web
? What's the name of your application? dashboard

Creating new Angular 2 Application: dashboard
Unable to find "@angular/cli" in devDependencies.

Please take the following steps to avoid issues:
"npm install --save-dev @angular/cli@latest" 

installing ng
  create .editorconfig
  create README.md
  create src/app/app.component.css
  create src/app/app.component.html
  create src/app/app.component.spec.ts
  create src/app/app.component.ts
  create src/app/app.module.ts
  create src/assets/.gitkeep
  create src/environments/environment.prod.ts
  create src/environments/environment.ts
  create src/favicon.ico
  create src/index.html
  create src/main.ts
  create src/polyfills.ts
  create src/styles.css
  create src/test.ts
  create src/tsconfig.app.json
  create src/tsconfig.spec.json
  create src/typings.d.ts
  create .angular-cli.json
  create e2e/app.e2e-spec.ts
  create e2e/app.po.ts
  create e2e/tsconfig.e2e.json
  create .gitignore
  create karma.conf.js
  create package.json
  create protractor.conf.js
  create tsconfig.json
  create tslint.json
Successfully initialized git.
Installing packages for tooling via npm.
npm WARN prefer global node-gyp@3.6.0 should be installed with -g

Package install failed, see above.

Application Status Code: 1

events.js:163
      throw er; // Unhandled 'error' event
      ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at child.Base.destinationPath (/usr/lib/node_modules/@mean-expert/fireloop/node_modules/yeoman-generator/lib/index.js:637:28)
    at child.install (/usr/lib/node_modules/@mean-expert/fireloop/node_modules/generator-fireloop/generators/ng2web/index.js:66:25)
    at Object.<anonymous> (/usr/lib/node_modules/@mean-expert/fireloop/node_modules/yeoman-generator/lib/index.js:408:23)
    at /usr/lib/node_modules/@mean-expert/fireloop/node_modules/run-async/index.js:25:25
    at /usr/lib/node_modules/@mean-expert/fireloop/node_modules/run-async/index.js:24:19
    at /usr/lib/node_modules/@mean-expert/fireloop/node_modules/yeoman-generator/lib/index.js:409:9
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)

**Comment by FishTheOriginal** [comment]
I noticed the message asking to install @angular-cli

- I uninstalled the global install
- Local install
- Reinstalled the local as instructed

Result:



     _-----_     ╭──────────────────────────╮
    |       |    │   Welcome to FireLoop!   │
    |--(o)--|    │  The MEAN Stack Platform │
   `---------´   │      by MEAN Expert      │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? What do you want to do? Generate Angular2 Client
Enable NativeScript 2 Support:
$ npm install -g nativescript
Enable Ionic 2 Support:
$ npm install -g cordova ionic
? What type of Angular 2 Application do you want to create? Angular 2 for Web
? What's the name of your application? dashboard


Creating new Angular 2 Application: dashboard
You cannot use the new command inside an Angular CLI project.

Application Status Code: 1

events.js:163
      throw er; // Unhandled 'error' event
      ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at child.Base.destinationPath (/usr/lib/node_modules/@mean-expert/fireloop/node_modules/yeoman-generator/lib/index.js:637:28)
    at child.install (/usr/lib/node_modules/@mean-expert/fireloop/node_modules/generator-fireloop/generators/ng2web/index.js:66:25)
    at Object.<anonymous> (/usr/lib/node_modules/@mean-expert/fireloop/node_modules/yeoman-generator/lib/index.js:408:23)
    at /usr/lib/node_modules/@mean-expert/fireloop/node_modules/run-async/index.js:25:25
    at /usr/lib/node_modules/@mean-expert/fireloop/node_modules/run-async/index.js:24:19
    at /usr/lib/node_modules/@mean-expert/fireloop/node_modules/yeoman-generator/lib/index.js:409:9
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)

**Comment by TuNi54** [comment]
the same here.
any suggestion ? 
ty

**Comment by jonathan-casarrubias** [comment]
Hi Guys, thanks for reaching out...

Here is the thing... The FireLoop CLI leverage the Angular CLI functionality and does install it as sub package for you...

But I have seen many issues after the old Angular CLI was renamed from angular-cli to @angular/cli, but both provides the same "ng" command, some nasty things started to happen.

Right now you might have conflicts with that specific problem....

To fix this you will need to start fresh by

1.- Making sure you remove the old angular-cli 
2.- You can or not install the new @angular/cli package the FireLoop CLI can work in both scenarios
3.- You need to remove any generated angular cli app and create it again (Back Up any work you might have)
4.- Within the yo-rc.json file within the root of the project you need to remove any angular client registered in there.
5.- Create a new angular app

I hope this information helps you fix your problem, which I also went through...

Cheers
Jon

**Comment by FishTheOriginal** [comment]
**Solution**: 

To fix this you will need to start fresh by

1.- Making sure you remove the old angular-cli
2.- You can or not install the new @angular/cli package the FireLoop CLI can work in both scenarios
3.- You need to remove any generated angular cli app and create it again (Back Up any work you might have)
4.- Within the yo-rc.json file within the root of the project you need to remove any angular client registered in there.
5.- Create a new angular app

Thanks Jon

Closing the issue.

**Comment by patricknazar** [comment]
This does not work for me
