### ISSUE TITLE
Any considerations for Electron as a client target?

### ISSUE THREAD

**Issue by proreact-mj** [mean-expert-official/fireloop.io#84]
#### What type of issue are you creating?
- [ ] Bug
- [X] Enhancement
- [ ] Question

#### What version of this module are you using?
- [X] 2.1.0-beta.n (2.1 Beta n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:
Considering: 
Loopbacks isomorphinc nature 
The multitarget approach of Fireloop (nativescript and webapp)
Angular 2 strong functionality to support complex large-scale apps with JIT (or AOT?)
I think it would be a natural evolution of Fireloop to consider Electron as a client target along with nativescript mobile platform and webapp targets. 

I'm not sure if there are any obvious problems that I'm missing, but on paper I think it looks like a match made in heaven and would allow Fireloop to be truly omnitarget and further leverage the offline capabilities that Loopback provides along with the multitarget capabilities of electron (Win\Mac\Linux and even some limited(?) ARM support)

**Comment by jonathan-casarrubias** [comment]
Hi @proreact-mj yeah well the automatically generated SDK should work in most of the cases within an electron environment, there might be issues related to the local storage, but I'm assuming that using the SDK for NodeJS should make it run in electron, though is just an assumption I never really tried..

Other than that in theory the rest of the features should work just right away....

We might want to test in a near future after the V1 stable is released, I think it should be matter of days
