### ISSUE TITLE
Real Time Stats Example frontend Angular2 error

### ISSUE THREAD

**Issue by Britskiy** [mean-expert-official/fireloop.io#93]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [x] Other

Write other if any:
1.0.0-beta.2.4

#### Please add a description for your issue:

Hello. I'm trying to follow the example at the [link](https://github.com/mean-expert-official/fireloop.io/wiki/Real-Time-Stats-Example). When I'm cloning the example repository, I'm not working, if I start doing it myself Then "something works" if you add to `component-config.json` code
`
"@mean-expert/loopback-component-realtime": {
    "debug": false,
    "auth": false,
    "driver": {
      "name": "socket.io"
    },
    "modules": [
      "IO",
      "PubSub",
      "FireLoop",
      "WebRTCSignaler"
    ]
  }`

When starting the application, I see an error in the browser "_ERROR TypeError: Can not read property 'ref' of undefined_". And really at check in object `rt` (argument of the constructor) I do not see object `FireLoop`.

So how can I run example? (

**Comment by jonathan-casarrubias** [comment]
@Britskiy I believe the real time stats repo example is a little outdated, try with this other repo which is up to date, https://github.com/mean-expert-official/fire-starter

Just to give you some context about that problem, now the references need to be created inside the onReady method.


````js
  constructor (rt: RealTime) {
    rt.onReady().subscribe(() => {
       // Create references here....
    })
  }
````

Cheers
Jon
