### ISSUE TITLE
Fireloop Offline Sync?

### ISSUE THREAD

**Issue by hasahmad** [mean-expert-official/fireloop.io#94]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [•] Question

#### Please add a description for your issue:
Is there are offline sync implementation?
I am building an app which fetches data from FireLoop api and saves to Sqlite, but i wanted to check if there is anything that Fireloop provides.

**Comment by jonathan-casarrubias** [comment]
Hi @hasahmad thanks for reaching out...

Hey so, the short answer is not really, it just provides with a basic Storage Service that would allow you to persist  in local storage.


We might add the offline sync in a future as built in feature, so I will keep this open and see how much support from the community it has..

Cheers
Jon

**Comment by dmastag** [comment]
This would be a killer feature if implemented

**Comment by roccolucatallarita** [comment]
Thanks, very useful!

**Comment by WhatzzUp** [comment]
+1

**Comment by tohagan** [comment]
You might want to have a look at [Loopback 3 Offline Sync](https://loopback.io/doc/en/lb3/Synchronization.html)

**Comment by mahnuh** [comment]
+1

**Comment by tohagan** [comment]
Another potential stratgey for this might be [Loopback <=> CouchDb](https://github.com/strongloop/loopback-connector-couchdb2) (store) <=> [PouchDb](https://pouchdb.com/) (client) 
- Here's my rant about [CouchDb/PouchDb as an alternative to Firebase](https://stackoverflow.com/questions/25990048/offline-firebase/30044230#30044230) that covers lots of stuff.

**Comment by jonathan-casarrubias** [comment]
Hi guys

Hey so, I really want to apologize for saying this but I'm stopping the support for FireLoop or any LoopBack module I built.

I'm working on a new project from scratch that of course is not built on top of LoopBack or anything else, this new project will also provide a SDK but now it won't be FrameWork specific, therefore you should be able to use it in Angular 5, React, Vue or even plain JavaScript projects


I apologize if you started a project on FireLoop, here I give a more detailed explanation:
https://github.com/mean-expert-official/fireloop.io/issues/137
