### ISSUE TITLE
fireloop referece reomte method/ onRemote method example

### ISSUE THREAD

**Issue by rajweb** [mean-expert-official/fireloop.io#95]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [ *] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [ ] Other

Write other if any:
1- how to query using remote method and also broadcast using remote method.
2- angular2 nested reactive form submission example using fireloopRef submit.
#### Please add a description for your issue:

**Comment by pmc-sstaehle** [comment]
Hi @rajweb, did you already find a solution for this?

**Comment by jonathan-casarrubias** [comment]
Hi guys

Hey so, I really want to apologize for saying this but I'm stopping the support for FireLoop or any LoopBack module I built.

I'm working on a new project from scratch that of course is not built on top of LoopBack or anything else, this new project will also provide a SDK but now it won't be FrameWork specific, therefore you should be able to use it in Angular 5, React, Vue or even plain JavaScript projects


I apologize if you started a project on FireLoop, here I give a more detailed explanation:
https://github.com/mean-expert-official/fireloop.io/issues/137
